### ISSUE TITLE
add StollyStruct ollydbg v1 plugin

### ISSUE THREAD

**Issue by doomedraven** [mandiant/flare-vm#128]
This brings support of structures like in ollyv2 but just for v1 :)

https://tuts4you.com/download/1275/

<img width="747" alt="captura de pantalla 2018-09-13 a las 15 05 50" src="https://user-images.githubusercontent.com/1856495/45490623-e5388080-b767-11e8-86b3-64a80ad6f7b2.png">

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
