### ISSUE TITLE
the application was unable to start correctly

### ISSUE THREAD

**Issue by Phexcom** [mandiant/flare-vm#190]
This might not be related to Flare, I need help with the Binaries From "PMAlabs". 

Trying to run some of the Binaries i get Errors like

 _the application was unable to start correctly(0xc0000005) _ 
_the application was unable to start correctly(0xc0000018) _ 

I Have tried on Windows XP and Windows 7 Sp1, I have tried all updates  But still i can't get this right, And there aint much solution about this online.........

**Comment by htnhan** [comment]
@Phexcom

Which binaries causes those issues? How did you run them?

**Comment by Phexcom** [comment]
All the Binaries. I have tried running output the same errors.
![Error](https://i.imgur.com/VqwU86c.png)

**Comment by tugzen** [comment]
I have the same problem and already spent a few days but couldn't find any soluton yet. If you find a solution and if you can share I will really appreciate my friend.

Thanks

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
