### ISSUE TITLE
Metasploit installer not found.

### ISSUE THREAD

**Issue by htnhan** [mandiant/flare-vm#203]

**Comment by htnhan** [comment]
We are aware that Metasploit pushes out update very regularly, which causes the installer to fails often. We are working a permanent solution. Currently, we can't use the metasploitframework-latest.msi since we can not verify the hash using a different source other than the .asc file available on metasploit server. We also can not/should not include the entire metasploit installer in our chocolatey package. Any recommendation to address this is welcome.

**Comment by hairlessbear** [comment]
Could you use `msfupdate` to update metasploit instead of doing it via Chocolatey? 

Something along the lines of pinning the version of metasploit used by the installer to fix the hash problem, then using `msfupdate` to keep metasploit up to date.

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
