### ISSUE TITLE
Password Required for Windows 8.1

### ISSUE THREAD

**Issue by lawiet47** [mandiant/flare-vm#228]
I tried to install FlareVM on a fresh Windows 8.1 Pro numerous times, however the automatic reboot doesn't work and I am asked to enter my password in every reboot. When the installation is completed I don't see a lot of packages that I would normally see when I install FlareVM on Windows 7.

**Comment by htnhan** [comment]
@lawiet47  Can you provide the exact screenshot or logs of the install? The auto reboot and login feature comes from BoxStarter, and it works on Windows 7 and windows 10 for our tests. I have not tested the install on 8.1, but it should work as expected.

During the install, do you see any errors? And, what packages don't get installed?

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
