### ISSUE TITLE
IDA 7.0 Free Not Installed

### ISSUE THREAD

**Issue by urain** [mandiant/flare-vm#231]
The machine enters a reboot loop with the flare-vm script trying to install IDA 7.0 Free. It downloads it on each attempt, tries to install it, says it could not install it, and then reboots the system. If you exit the script you can stop the loop, but IDA 7.0 Free won't be installed. Also suggest only installing IDA 7.0 Free and skip installing IDA 5.0 Free altogether.

**Comment by htnhan** [comment]
@urain Do you have the exact error that cause IDA Free 7.0 to fail?

IDA 5.0 is still installed by default since IDA Free 7.0 is 64bit. We would like to provide a disassembler on 32bit systems as well, hence IDA Free 5.0

**Comment by mt025** [comment]
I have a similar issue that may be related to this. Here is a screenshot for reference. Any applications after IDA 7.0 are not installed.

![image](https://user-images.githubusercontent.com/2631330/64963605-710c4d80-d891-11e9-8f5f-af6ba9015c5e.png)

**Comment by htnhan** [comment]
@mt025 This is more likely related to an issue with chocolatey or boxstater (example issue here: `https://github.com/chocolatey/choco/issues/1361`). However, we have a temporary fix in windows 10 already.
