### ISSUE TITLE
Downloaded file name length is more than 256 characters

### ISSUE THREAD

**Issue by Naganathansj** [mandiant/flare-vm#240]
![image](https://user-images.githubusercontent.com/54846785/64172284-39a1a800-ce72-11e9-9b58-fd84da766dc1.png)

**Comment by Naganathansj** [comment]
My Environment is Win7_64

**Comment by mt025** [comment]
I think it may be similar to the issue I'm facing regarding IDA here: #231

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
