### ISSUE TITLE
How to Install docker version of thug.py and ViperMonkey?

### ISSUE THREAD

**Issue by opticoax747** [mandiant/flare-vm#262]
Tried installing both, but they threw a bunch of errors.

I see there is an Amass docker available, but can we install the docker for thug.py and ViperMonkey for better macro/suspicious URL analysis?

**Comment by htnhan** [comment]
@opticoax747  Docker is only supported if you are using windows 10. You also need specific hardware and config on your host and your hypervisor to supported nested virtualization. For more details, please refer to the following issue in the Commando VM repo: https://github.com/fireeye/commando-vm/issues/94

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
