### ISSUE TITLE
Add NetworkMiner

### ISSUE THREAD

**Issue by erik4711** [mandiant/flare-vm#264]
https://www.netresec.com/?page=NetworkMiner

I'd be happy to help get NetworkMiner included in the "Networking" or "Forensic" category of FLARE VM.

**Comment by opticoax747** [comment]
Doesnt wireshark have some innate file extraction tools?

**Comment by erik4711** [comment]
The supported file transfer protocols in Wireshark’s “File, Export Objects” menu are HTTP, IMF, SMB and TFTP. NetworkMiner automatically extracts files from FTP, TFTP, HTTP, HTTP/2, SMB, SMB2, SMTP, POP3 and IMAP traffic when a capture file is loaded.

Many incident responders also like the “Hosts” tab in NetworkMiner, which provides a nice overview of the hosts that have communicated in the loaded PCAP file(s). The hosts view shows the results of NetworkMiner’s OS fingerprinting, which ports are open, JA3 hashes and a great deal of other meta data about each observed IP address.

You can find some screenshots of NetworkMiner’s Hosts tab in the [NetworkMiner 2.5 release](https://netresec.com/?b=19B4a1a) blog post.

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.

**Comment by erik4711** [comment]
It looks as if @vm-packages closed all (100+) open issues with the exact same comment without checking whether or not the reported issues were fixed in the new release.
