### ISSUE TITLE
Include NoFuserEx in flare-vm installation

### ISSUE THREAD

**Issue by edevil** [mandiant/flare-vm#266]
It would be great to include NoFuserEx in the installation since it doesn't even provide a binary in the official repo.

Maybe a new chocolatey package with a compiled version?

**Comment by turbosmurfen** [comment]
Yes it would be nice with NoFuserEX. Also the rest of the tools too.
ConfuserExCallFixer, ConfuserExceptionsRestore, ConfuserExCfgKiller, ConfuserExConstantDecryptor, ConfuserExDupPopPatcher, ConfuserExExpressionKiller, ConfuserExFixer, ConfuserExSwitchKiller, ConfuserExStringDecrypter. I have these, if someone can't find the sources.

**Comment by DreammsOnUpdate** [comment]
> Yes it would be nice with NoFuserEX. Also the rest of the tools too.
> ConfuserExCallFixer, ConfuserExceptionsRestore, ConfuserExCfgKiller, ConfuserExConstantDecryptor, ConfuserExDupPopPatcher, ConfuserExExpressionKiller, ConfuserExFixer, ConfuserExSwitchKiller, ConfuserExStringDecrypter. I have these, if someone can't find the sources.

can you share this sources with me? And also how am I supposed to use these? I mean for example which one should I use first and which one should I use second .etc

**Comment by turbosmurfen** [comment]
Here is the files, https://file.io/nIijZnVquuel (Please test them in a VM)

**Comment by turbosmurfen** [comment]
> 
> 
> > Yes it would be nice with NoFuserEX. Also the rest of the tools too.
> > ConfuserExCallFixer, ConfuserExceptionsRestore, ConfuserExCfgKiller, ConfuserExConstantDecryptor, ConfuserExDupPopPatcher, ConfuserExExpressionKiller, ConfuserExFixer, ConfuserExSwitchKiller, ConfuserExStringDecrypter. I have these, if someone can't find the sources.
> 
> can you share this sources with me? And also how am I supposed to use these? I mean for example which one should I use first and which one should I use second .etc

Here is the files, https://file.io/nIijZnVquuel (Please test them in a VM)

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
