### ISSUE TITLE
FlareVM taking over 12 hrs to install

### ISSUE THREAD

**Issue by Mondea** [mandiant/flare-vm#283]
I started installation yesterday evening, hoping it would be done by then. It wasnt, i left it on installing overnight and i woke up and it still is running the installation. It seems nothing much is installing tho. 

It keeps quickly going through the the installation over and over again.
And every one of the installations are Chocolatey upgraded 0/1 packages. 0 packages failed. See the log for details. It does this for the various programs it is set to install.

It looked to me as if it was just trying to install something that is already installed. I closed the cmd window. However the problem now is that whenever i start my VM, it automatically logs in (even tho it had password on before i ran flare), and runs the installation CMD automatically. How do i stop this?

**Comment by bonkerslm10** [comment]
any solution for this? I'm facing the same issue
