### ISSUE TITLE
burp-suite-free-edition Error

### ISSUE THREAD

**Issue by Buffer-Kills** [mandiant/flare-vm#284]
burp-suite-free-edition v2020.2.1 [Approved]
burp-suite-free-edition package files upgrade completed. Performing other installation steps.
Downloading burp-suite-free-edition
  from 'https://portswigger.net/Burp/Releases/Download?productId=100&version=2020.2.1&type=jar'
Downloading burp-suite-free-edition
  from 'https://portswigger.net/Burp/Releases/Download?productId=100&version=2020.2.1&type=jar'
Progress: 0% - Saving 2.95 MB of 331.26 MB                                                                                                                                                                                                  Chocolatey timed out waiting for the command to finish. The timeout
 specified (or the default value) was '2700' seconds. Perhaps try a
 higher `--execution-timeout`? See `choco -h` for details.
Error computing hash for 'C:\ProgramData\chocolatey\lib\burp-suite-free-edition\tools\app\burpsuite.jar'
 Hash will be special code for locked file or file too big instead.
 Captured error:
  The process cannot access the file 'C:\ProgramData\chocolatey\lib\burp-suite-free-edition\tools\app\burpsuite.jar' because it is being used by another process.
The upgrade of burp-suite-free-edition was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\burp-suite-free-edition\tools\chocolateyInstall.ps1'.
 See log for details.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 (5) Access is denied: [\\?\C:\ProgramData\chocolatey\lib-bad\burp-suite-free-edition]
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 (5) Access is denied: [\\?\C:\ProgramData\chocolatey\lib-bad\burp-suite-free-edition]
Maximum tries of 3 reached. Throwing error.
Move failed with message:
 (5) Access is denied: [\\?\C:\ProgramData\chocolatey\lib-bad\burp-suite-free-edition]
 Attempting backup move method.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 (32) The process cannot access the file because it is being used by another process: [\\?\C:\ProgramData\chocolatey\lib-bad\burp-suite-free-edition\tools\app\burpsuite.jar]
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 (32) The process cannot access the file because it is being used by another process: [\\?\C:\ProgramData\chocolatey\lib-bad\burp-suite-free-edition\tools\app\burpsuite.jar]
Maximum tries of 3 reached. Throwing error.
Could not move bad package to failure directory It will show as installed.
 C:\ProgramData\chocolatey\lib\burp-suite-free-edition
 The error:
 (32) The process cannot access the file because it is being used by another process: [\\?\C:\ProgramData\chocolatey\lib-bad\burp-suite-free-edition\tools\app\burpsuite.jar]
[NuGet] Installing 'burp.free.fireeye 1.7.36.7'.
[NuGet] Successfully installed 'burp.free.fireeye 1.7.36.7'.

burp.free.fireeye v1.7.36.7
burp.free.fireeye package files upgrade completed. Performing other installation steps.
 The upgrade of burp.free.fireeye was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey upgraded 1/2 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - burp-suite-free-edition (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\burp-suite-free-edition\tools\chocolateyInstall.ps1'.
 See log for details.
Chocolatey reported an unsuccessful exit code of -1. See C:\Users\Vedanth\AppData\Local\Boxstarter\boxstarter.log for details.

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
