### ISSUE TITLE
Some packages not installed on fresh installation

### ISSUE THREAD

**Issue by sei-jvessella** [mandiant/flare-vm#286]
On Windows 10 Enterprise, version 1909 (OS Build 18363.752).

I did a fresh default Flare-VM install according to the README [here](https://github.com/fireeye/flare-vm#installation-install-script). As of the installation time and at this very moment, I have all possible updates according to Windows Update.

I noticed that I was missing Wireshark after the installation, so I wrote a Python script to check what packages were missing on install:

```
import json


with open('chocolist-beforemanual.txt') as f:
    before_lines = f.readlines()

before_lines = before_lines[1:]

with open('packages.json') as f:
    package_json = json.load(f)

package_names = []

for package in package_json['packages']:
    package_names.append(package['name'])

for pkg_name in package_names:
    shortened_pkg_name = pkg_name.lower().split('.')[0]


    found = False
    for line in before_lines:
        name, *etc = line.strip().split()
        if shortened_pkg_name in name.lower():
            found = True
            break
    if not found:
        print(shortened_pkg_name)
```

The "chocolist-beforemanual.txt" file was generated with the PowerShell command `choco list -lo | Out-File .\chocolist-beforemanual.txt -Encoding utf8` and the "packages.json" is just a copy of [this](https://github.com/fireeye/flare-vm/blob/master/flarevm.installer.flare/tools/packages.json).

Here are the packages that were not installed:
de4dot
volatility
wireshark
exeinfope
cyberchef
procdot
cygwin
fiddler

Of these, only `fiddler`, `cygwin`, `volatility`, and `wireshark` installed successfully. `wireshark` timed out on the first attempt, but then installed successfully on the second try.

`de4dot`, `exeinfope`, `cyberchef`, and `procdot` all failed.
`de4dot` says that it's "Likely broken for FOSS users (due to download location changes)" and that seems correct.

`exeinfope`, `cyberchef`, and `procdot` all say that they were not found with the sources listed (Both in Chocolatey and FireEye's).

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
