### ISSUE TITLE
add x64dbg plugin manager

### ISSUE THREAD

**Issue by doomedraven** [mandiant/flare-vm#293]
https://github.com/horsicq/x64dbg-Plugin-Manager

**Comment by doomedraven** [comment]
that allows you to install plugins and one of them is https://github.com/LFriede/x64dbg-updater that allows you to easilly upgrade x64dbg to latest version as in flare-vm isn't lastest one, so i think it also will simplify your life, i have manually installed on my side and works very well

![image](https://user-images.githubusercontent.com/1856495/81497580-af8ec680-92bf-11ea-805d-f287a0ddf64e.png)

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
