### ISSUE TITLE
Bytecode Viewer fails to open apk

### ISSUE THREAD

**Issue by Ana06** [mandiant/flare-vm#299]
I get an error when trying to open an `.apk` in Bytecode Viewer:
```
Bytecode Viewer Version: 2.9.22, Preview Copy: false, Fat Jar: true, OS: Windows 7, Java: 1.8.0_251

java.io.FileNotFoundException: C:\Users\user\.Bytecode-Viewer\bcv_temp\NVDnkKznBGOfzfRzaoZiLCKoE.jar (The system cannot find the file specified)
     at java.io.FileInputStream.open0(Native Method)
     at java.io.FileInputStream.open(Unknown Source)
     at java.io.FileInputStream.<init>(Unknown Source)
     at the.bytecode.club.bytecodeviewer.util.JarUtils.loadClasses(JarUtils.java:168)
     at the.bytecode.club.bytecodeviewer.BytecodeViewer$8.run(BytecodeViewer.java:961)
```
The solution seems to be to run Bytecode Viewer as admin (See details in https://github.com/Konloch/bytecode-viewer/issues/227#issuecomment-633886725). For example by executing in a cmd opened as administrator the following line:

`java -jar  C:\ProgramData\chocolatey\lib\bytecode-viewer.flare\tools\Bytecode-Viewer-2.9.22.jar`

I think that making it the default to run Bytecode Viewer as admin in FlareVM would avoid that other people run into the same issue.

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
