### ISSUE TITLE
python 3 upgrade failed

### ISSUE THREAD

**Issue by kasper45** [mandiant/flare-vm#301]
Hi! How can i upgrade python3 package with choco or cinst?

error
Updating 'python3 3.7.2' to 'python3 3.8.3' failed. Unable to find versions of 'libraries.python2.fireeye, libraries.python3.fireeye' that are compatible with 'python3 3.8.3'.

**Comment by htnhan** [comment]
@kasper45  We recently updated FLARE-VM, please try again to see if you still have issues updating Python

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
