### ISSUE TITLE
[Feature Request] Ability to only install Open Source Tools

### ISSUE THREAD

**Issue by 3lpsy** [mandiant/flare-vm#302]
It would be nice if tools were tagged as either proprietary/freeware or open source (free as in freedom). It doesn't have to be default but the install script could expose a flag like '-opensource' or '-free' (though '-free' is sort of confusing on Windows due to how common freeware is). The benefits is that end users would know that the tools they are using could be audited and are (potentially) expandable. 

This feature could also be rolled into a more general "tagging" feature.

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
