### ISSUE TITLE
install.ps1 script should print a useful error when it doesn't detect powershell 5 on the system

### ISSUE THREAD

**Issue by bcheeves** [mandiant/flare-vm#303]
It was generating a lot of errors running the script and I had to dig into the code and review the readme to find that I'm missing powershell5 on the system and find that was wrong. It should have a system check prior to running that complains if you are missing the proper dependencies.

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
