### ISSUE TITLE
Flare VM installer should check disk space requirements

### ISSUE THREAD

**Issue by bcheeves** [mandiant/flare-vm#304]
I had a 35GB system partition, didn't even realize it due to the VM template that I deployed on the system either, but it failed almost 2/3 of the way through the install with exceptions saying  'There is not enough space on the disk'.  It would be better to have the script check that there is plenty of free disk space first, before installing.  It would also help if there was a list of disk space requirements in the documentation on installing it.

<img width="1041" alt="disk_space_full" src="https://user-images.githubusercontent.com/17578600/84459353-12a3ae00-ac1c-11ea-9bf8-b147c7ef4979.png">

**Comment by kodaman2** [comment]
This is really a chocolatey issue more than anything, nothing flare vm can do about it. Most packages aren't really packages in a sense of what you would normally see in python pip packages or apt-get. Most of them are just scripts pulling dependencies from different sites it would be nearly impossible to calculate sizes prior to installation. 

Read link below. 

https://github.com/chocolatey/choco/issues/701

PS: A windows vm should be 60 -100+ to get any real work done. I wouldn't give my worst enemy a windows vm with 35GB.
