### ISSUE TITLE
Flare VM installer should ask if you want to specify where to download the packages to install

### ISSUE THREAD

**Issue by bcheeves** [mandiant/flare-vm#305]
This would be a useful feature to have in the case where the system is setup with multiple disk partitions and they want to control where the packages are downloaded.

use case is an environment is a VM deployed on Vcloud with two partitioned disk drives.
c: is windows system partition, 30GB in size (for OS)
d: is 200 GB in size (for storage of downloads, tools, malware storage, etc and will eventually be setup as read-only on the system)

I did not see system requirements for disk space when installing on a VM. I executed the installer, and it got 2/3rd of the way through and threw an exception on a disk space error, which I logged another issue for, but I noticed that it is downloading all the system packages to a temp folder under %appdata%\Local\NuGet, %appdata%\Local\ChocoCache, and %appdata%\Local\Boxstarter, as well under %temp%\Chocolatey. When cloned this VM, it had only a 30GB partition space, so I chose to add another disk which I was going to use for most of the storage, but it never prompted me.

**Comment by reg-reginald** [comment]
This might be good idea because the HD could be copied and when doing refresh of the 90 day Windows evaluation licence the HD could be attached to it rather than going through the  installation process again 

Might have issues with PATH though

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
