### ISSUE TITLE
xorsearch.flare referencing old link

### ISSUE THREAD

**Issue by zin1x** [mandiant/flare-vm#306]
> xorsearch.flare v1.11.2.2
> xorsearch.flare package files install completed. Performing other installation steps.
> Attempt to get headers for https://didierstevens.com/files/software/XORSearch_V1_11_2.zip failed.
>   The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://didierstevens.com/files/software/XORSearch_V1_11_2.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
> Downloading xorsearch from 'https://didierstevens.com/files/software/XORSearch_V1_11_2.zip'
> 
> ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://didierstevens.com/files/software/XORSearch_V1_11_2.zip'. Exception calling "GetResponse"with "0" argument(s): "The remote server returned an error: (404) Not Found."
> 
> The install of xorsearch.flare was NOT successful.
> 

Old link dont exist. The new link is at http://didierstevens.com/files/software/XORSearch_V1_11_3.zip

**Comment by m0n4** [comment]
https://github.com/DidierStevens/FalsePositives/raw/master/XORSearch_V1_11_4.zip

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
