### ISSUE TITLE
Several packages failed to install on Win7x64

### ISSUE THREAD

**Issue by captainproton795** [mandiant/flare-vm#309]
Fresh Win7 x64
VMWare Workstation
Fully patched and updated as time of writing this.
-------------------------------------------------------

The following packages failed to install:
1. ppee.fireeye
  >  Says ERROR: The remote file either doesn't exist, is unauthorized or is forbidden from url 'https://www.mzrst.com/puppy/PPEE(puppy)%201.12.zip'  Exception calling "GET RESPONSE"....... Unsuccessful exit code 404

2. libraries.python2.fireeye - yara-python
                                           - mkyara
  > unsuccessful exit code of 1

3. x64dbg.py.flare
  > 404 not found same as above

4. binary ninja demo
  > did not pass hash check (sha256)

5. dnsSpy.flare
  > 404 not found same as above

6. vb_decompiler_lite
  > did not pass hash check (sha256)

I didn't have any of these issues a month or two back when installing FlareVM onto Win10, are these possibly Win7 issues or incompatibilities? 

Thanks!

**Comment by divinehand** [comment]
Scratch that date I mentioned.  I actually just setup on W10 on July 6th, about a week ago with no errors to speak of.

**Comment by doomedraven** [comment]
i saw today dnsSpy problem, they changed the way to store release on github, now they use autobuilds via github actions, is why it returns 404

**Comment by MalwareMechanic** [comment]
Thanks for reporting these -- package maintenance is always a moving target!

**Comment by Asadoxian** [comment]
I have had exactly the same packages fail to install on both Windows 10 and Windows 7 x64

**Comment by tom-ss** [comment]
Where did you get windows 7 64bits ????

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
