### ISSUE TITLE
No background set - no shortcuts - no env vars

### ISSUE THREAD

**Issue by ntrnflxlbs** [mandiant/flare-vm#312]
completed the install and didn't get the background or taskbar shortcuts. rebooted a few times. tried cup all. 
re-ran the install PS1 a few times. no change. Found on the commando VM you could attempt to fix it by doing a cinst -y commandovm.win10.config.fireeye but I do not see anything similar for FLARE. 
I also do not have the env vars set properly along with the missing taskbar shortcuts and background so it points to a bigger issue with environment configuration. highly likely i'm missing something. Using the latest downloaded win 10 x64 IE/Edge testing VM from the Ms website.

**Comment by ntrnflxlbs** [comment]
it also appears FLOSS was never deployed anywhere on the system

**Comment by davehull** [comment]
I'm also looking for floss on v2 and not finding it. I also tried `cinst floss` with no luck.

**Comment by MalwareMechanic** [comment]
We currently test with Win7, so you may notice some issues with Win10 (shortcuts have become a pain point) -- though that's on our roadmap to support. I'd recommend checking if the environment variables were set correctly. Here' s a list of the common env. vars: https://github.com/fireeye/flare-vm/blob/master/profile.json#L3-L5

Try reinstalling FLOSS with `cinst floss.python.flare`

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
