### ISSUE TITLE
Unable to connect to remote  'https://www.myget.org/F/fireeye/api/v2' during FlareVM install

### ISSUE THREAD

**Issue by FLAnalyst** [mandiant/flare-vm#314]
In my attempts to install FlareVM I receive these errors.  I assume the inability to get to the remote server is the reason for the second error.  I have queried and googled to find an answer or work around and have been unsuccessful.  Any assistance is greatly appreciated.

An error occurred while loading packages from 'https://www.myget.org/F/fireeye/api/v2': Unable to connect to the remote server

{Chocolatey reported an unsuccessful exit code of 1.

**Comment by htnhan** [comment]
@FLAnalyst, Sorry for the late reply. Unfortunately, the error you give is pretty generic. It may mean any of the following:
1. There is some issue with `myget.org` at that moment. In this case, all you need to do is try  the installation again. Hopefully they fix the issue:
2. There is some issue with the network connectivity. In this case, you can also try to install at a later time after fixing network issue
3. There is some bug with the install script. In this case, we would need more information from the logs file within: C:\ProgramData\chocolatey\logs\

**Comment by Maijin** [comment]
Would be good to have a check at the beginning on the script to check various connectivity. It's currently down per @ztormhouse

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
