### ISSUE TITLE
stringsifter failed to install due to dependency issue with python 3.8

### ISSUE THREAD

**Issue by MohamedEl-Hadidi** [mandiant/flare-vm#323]
- VM Info:
------------
- Windows 10
- Version 1909 (OS Build 18363.1082)
-------------------------------------------------------------------------------------------------------------------------------------------
- Error shown in module_output.txt:
----------------------------------------
Building wheels for collected packages: numpy, scikit-learn
  Building wheel for numpy (setup.py): started
  Building wheel for numpy (setup.py): still running...
  Building wheel for numpy (setup.py): finished with status 'error'
py :   ERROR: Command errored out with exit status 1:
At line:1 char:1
+ py -3 -m pip install stringsifter 2>&1 >> C:\ProgramData\chocolatey\l ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (  ERROR: Comman... exit status 1::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   command: 'C:\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Flare\\AppData\\Local\\Temp\\pip-install-kbcn8103\\numpy\\s
etup.py'"'"'; __file__='"'"'C:\\Users\\Flare\\AppData\\Local\\Temp\\pip-install-kbcn8103\\numpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code
=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Flare\AppData\Local\Temp\pip-wheel-6d
xyxgv5'
       cwd: C:\Users\Flare\AppData\Local\Temp\pip-install-kbcn8103\numpy\
  Complete output (2031 lines):
  Running from numpy source directory.
  blas_opt_info:
  blas_mkl_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries mkl_rt not found in ['C:\\Python38\\lib', 'C:\\', 'C:\\Python38\\libs']
    NOT AVAILABLE
  
  blis_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries blis not found in ['C:\\Python38\\lib', 'C:\\', 'C:\\Python38\\libs']
    NOT AVAILABLE
  
  openblas_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries openblas not found in ['C:\\Python38\\lib', 'C:\\', 'C:\\Python38\\libs']
  get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
  customize GnuFCompiler
  Could not locate executable g77
  Could not locate executable f77
  customize IntelVisualFCompiler
  Could not locate executable ifort
  Could not locate executable ifl
  customize AbsoftFCompiler
  Could not locate executable f90
  customize CompaqVisualFCompiler
  Found executable C:\ProgramData\chocolatey\bin\DF.exe
  customize IntelItaniumVisualFCompiler
  Could not locate executable efl
  customize Gnu95FCompiler
  Could not locate executable gfortran
  Could not locate executable f95
  customize G95FCompiler
  Could not locate executable g95
  customize IntelEM64VisualFCompiler
  customize IntelEM64TFCompiler
  Could not locate executable efort
  Could not locate executable efc
  customize PGroupFlangCompiler
  Could not locate executable flang
  don't know how to compile Fortran code on platform 'nt'
    NOT AVAILABLE
  
  atlas_3_10_blas_threads_info:
  Setting PTATLAS=ATLAS
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries tatlas not found in ['C:\\Python38\\lib', 'C:\\', 'C:\\Python38\\libs']
    NOT AVAILABLE
  
  atlas_3_10_blas_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries satlas not found in ['C:\\Python38\\lib', 'C:\\', 'C:\\Python38\\libs']
    NOT AVAILABLE
  
  atlas_blas_threads_info:
  Setting PTATLAS=ATLAS
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries ptf77blas,ptcblas,atlas not found in ['C:\\Python38\\lib', 'C:\\', 'C:\\Python38\\libs']
    NOT AVAILABLE
  
  atlas_blas_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries f77blas,cblas,atlas not found in ['C:\\Python38\\lib', 'C:\\', 'C:\\Python38\\libs']
    NOT AVAILABLE
  
--------------------------------------------------------------------------------------------------------------------------------------------
- Solution: 
------------
We installed python 3.7 and then installed stringsifter manually and it worked very well.

Reference: https://github.com/numpy/numpy/issues/13573

---------------------------------------------------------------------------------------------------------------------------------------------
- Recommendations:
-----------------------
The script should install python 3.7 besides 2.7 and 3.8 in order to maintain dependency for this package till the dependency issue solved.
Or upgrade stringsifter dependencies to be compatible with python 3.8.

**Comment by Wesly-Zhang** [comment]
I have the same issue.

**Comment by Derekt2** [comment]
same issue.

**Comment by RachelVB** [comment]
Hi, 
@MohamedEl-Hadidi
@Wesly-Zhang
@Derekt2

Hope this helps:
After much trial and error, I was finally able to install FlareVM successfully.

 - First off, I was UNABLE to install Flarevm in a Windows 10 edge virtual machine. So you need to install the Windows 7 edge version (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
- Update Powershell (https://github.com/PowerShell/PowerShell) to newest version since the current version is 2 in this VM.
- Manually install choco using the steps in this link (https://chocolatey.org/docs/installation). If I didn't do this step, flarevm would keep failing during install.
- Now run Flare vm using the script install steps.

Please note that stringsifter will still FAIL to install, however this did not matter and flarevm still installed successfully. 

Let me know if you need anymore help.

**Comment by MohamedEl-Hadidi** [comment]
Hi @RachelVB,
Thanks for your efforts, but I already installed Flare-VM on windows 10 successfully (Windows 10
Version 1909 (OS Build 18363.1082)) as I mentioned above it is already supported, I only face this dependency (stringsifter) error while installation and I solved it manually (install python 3.7) , So I shared this in order to be tracked as (dependency broken) bug.

**Comment by Wesly-Zhang** [comment]
> 
> 
> Hi,
> @MohamedEl-Hadidi
> @Wesly-Zhang
> @Derekt2
> 
> Hope this helps:
> After much trial and error, I was finally able to install FlareVM successfully.
> 
>     * First off, I was UNABLE to install Flarevm in a Windows 10 edge virtual machine. So you need to install the Windows 7 edge version (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
> 
>     * Since this VM does NOT come with WMF, you will have to install it here before you can proceed to the next step(https://www.microsoft.com/en-us/download/details.aspx?id=54616)
> 
>     * Update Powershell (https://github.com/PowerShell/PowerShell) to newest version since the current version is 2 in this VM.
> 
>     * Manually install choco using the steps in this link (https://chocolatey.org/docs/installation). If I didn't do this step, flarevm would keep failing during install.
> 
>     * Now run Flare vm using the script install steps.
> 
> 
> Please note that stringsifter will still FAIL to install, however this did not matter and flarevm still installed successfully.
> 
> Let me know if you need anymore help.

Hi，
Thank you for replying me. I install flare-vm in windows 7 sp1 ultimate x64. I don't  use windows 10. So just like what MohamedEI-Hadidi said, Maybe it need python 3.7 support to install.
Best Regards.

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
