### ISSUE TITLE
Help Please Powershell keeps giving me errors

### ISSUE THREAD

**Issue by iCorruptedX** [mandiant/flare-vm#328]
![image](https://user-images.githubusercontent.com/73658665/97600327-50dd1680-19df-11eb-8b6a-fe0afee01835.png)

**Comment by SyedHaris786** [comment]
Facing exactly the same errors

**Comment by htnhan** [comment]
Folks, sorry for the late reply. There was some network issues on the `MyGet` side. They have it up and down a few times a few weeks back. Please give the installation another try, and let me know if you still have errors.

**Comment by S-JM** [comment]
> Folks, sorry for the late reply. There was some network issues on the `MyGet` side. They have it up and down a few times a few weeks back. Please give the installation another try, and let me know if you still have errors.

I'm still having the same issue.

**Comment by S-JM** [comment]
The issue was caused by an older version of powershell, I upgraded to version 7 and I do no get those errors anymore. Please see issue 303 (https://github.com/fireeye/flare-vm/issues/303), a check should be added to the install script for the powershell version.

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
