### ISSUE TITLE
vbdecompiler.flare fails

### ISSUE THREAD

**Issue by zaqes** [mandiant/flare-vm#340]
vbdecompiler.flare fails for some reason, I can download the file manually though.

```
vbdecompiler.flare v11.6.0.1
vbdecompiler.flare package files upgrade completed. Performing other installation steps.
Attempt to get headers for https://www.vb-decompiler.org/files/vb_decompiler_lite.zip failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://www.vb-decompiler.org/files/vb
_decompiler_lite.zip'. Exception calling "GetResponse" with "0" argument(s): "The request was aborted: Could not create
SSL/TLS secure channel."
Downloading vbdecompiler
  from 'https://www.vb-decompiler.org/files/vb_decompiler_lite.zip'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://www.vb-decompiler.org/fil
es/vb_decompiler_lite.zip'. Exception calling "GetResponse" with "0" argument(s): "The request was aborted: Could not cr
eate SSL/TLS secure channel."
The upgrade of vbdecompiler.flare was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\vbdecompiler.flare\tools\chocolateyinstall.ps1'.
 See log for details.
```

**Comment by htnhan** [comment]
Hi @zaqes, `vbdecompiler` website likely updates their TLS certificate, which will cause installation on Windows 7 to fails. As of right now, we are unable to mitigate this. We are working on FLARE-VM support for Windows 10. That should fix this issue.

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
