### ISSUE TITLE
Issue to install in Azure

### ISSUE THREAD

**Issue by alexander-pick** [mandiant/flare-vm#346]
I tried to install a flareVM in our Azure environment and got the following error related to Windows Defender:

![azure_error](https://user-images.githubusercontent.com/656911/105207276-9c6b1080-5b47-11eb-8352-118e64ca7e3f.PNG)

Any idea how to solve this? The shell was elevated and the system is not member of a domain (not a AD or Azure Domain).

**Comment by htnhan** [comment]
Hi @alexander-pick , are you installing on Windows 10? If so, you need to disable Windows Defender manually before installing.

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
