### ISSUE TITLE
Installation always stuck at downloading wireshark 3.4.3... 99%

### ISSUE THREAD

**Issue by AmgdGocha** [mandiant/flare-vm#351]
I'm trying to install Flare VM and the installation always stuck at Progress: Downloading Wireshark 3.4.3... 99%
I've tried to install it on a win7 machine I have and also tried to install it on the iewin7 VM https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ and it stuck at the same point as shown in the screenshot 
![Screenshot_20210216_013653](https://user-images.githubusercontent.com/17185638/108002503-82163c80-6ff8-11eb-9280-b21a8b06ed3a.png)
any ideas please?

**Comment by AmgdGocha** [comment]
After almost two days of random trials and, the script has finished but as you can see in the screenshot, the VM background didn't change as what supposed to be done!
![Screenshot_20210216_040146](https://user-images.githubusercontent.com/17185638/108009888-4ab18b00-700c-11eb-83d2-8554e8b2321b.png)

**Comment by gabeaaaa** [comment]
<img width="1683" alt="fin__i_guess" src="https://user-images.githubusercontent.com/29171541/109158658-a9c87b80-7741-11eb-8267-a1846d4d2a98.png">

I am in the same position.

**Comment by htnhan** [comment]
Hi Folks, 

There are potentially three things that may cause this:

1. `myget.org` package repo may throttle download speed. Base on your screenshot, this looks like the main reason.
2. `wireshark` web server may be slow. 
3. Your internet connectivity may be slow, or your ISP may throttle the download.

Unfortunately, we are unable to address any of these potential issues.

@AmgdGocha, for the background, please confirm that your `Windows Theme` setting is `Aero Theme`, and not `Windows Basic`. In addition, another reboot may allow the background to refresh.

htnhan

**Comment by RyanNgCT** [comment]
@ICSGabe: Same issue here. @htnhan: if this persists can I terminate installation of the tools at this point? Or possible to exclude wireshark from being installed using the `ps1` (instead manual installation or using `cinst` later on?)

**Comment by htnhan** [comment]
Hi @RyanNgCT, when testing FLARE-VM, wireshark download is also pretty slow for me. However, eventually, it finishes without issue. To exclude `wireshark`, I recommend you check out our documentation on using a [custom profile](https://github.com/fireeye/flare-vm#customizing-packages)

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
