### ISSUE TITLE
python issue, follow up on #326

### ISSUE THREAD

**Issue by zaqes** [mandiant/flare-vm#353]
This is still an issue to me.

**Comment by htnhan** [comment]
Hi @zaqes, I'm sorry I missed that comment. I have added some replies there. In short, there are two options here:

1. Do not update Python and stay at 3.7.x
2. Install FLARE-VM on Windows 10.

**Comment by zaqes** [comment]
Can this not be excluded when running "cup all" on Windows 7?

**Comment by htnhan** [comment]
As far as I know, `cup all` will try to update all packages, including python3 package. You can `cup libraries.python3.fireeye` to only update the libraries instead.

**Comment by zaqes** [comment]
What I meant was if this newer python version can't be excluded from Windows 7 installations when you do cup all?

**Comment by htnhan** [comment]
@zaqes , can you elaborate a bit more? As far as I know, Python 3.8 does not support Windows 7 any more. FLARE-VM has to limit the Python version to 3.7 to keep Windows 7 support. 

I don't think I know if a way to exclude Python when you perform `cup all`. I think `cup all` will try to update everything to the latest version, including Python

**Comment by zaqes** [comment]
Ok, if there's no way to exclude a newer version on a specific OS I assume this issue cannot be resolved?

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
