### ISSUE TITLE
[Feature Request]: Add progress bar for installation

### ISSUE THREAD

**Issue by RyanNgCT** [mandiant/flare-vm#356]
Not sure if this is possible but it would be very helpful to have one to estimate the time needed until installation completes (for the entire installation, not just the individual components). Thanks!

**Comment by RyanNgCT** [comment]
Perhaps functions such as installing only specific components that a user needs could be added also to speed up the installation process (rid programs unnecessary to one's workflow)

**Comment by MalwareMechanic** [comment]
Hey @RyanNgCT,

You can actually select which packages you want to install! See: https://github.com/fireeye/flare-vm#customizing-packages

**Comment by RyanNgCT** [comment]
I was talking more about something like a GUI installer like [this](https://github.com/mentebinaria/retoolkit). So the progress bar can be considered?

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
