### ISSUE TITLE
DNS Resolution errors on internet connected VM - can't install commandovm.win10.installer.fireeye

### ISSUE THREAD

**Issue by cf-jm** [mandiant/flare-vm#361]
# Setup:
- VMWare Fusion 12.1.1, NAT networking
- Operating Systems attempted (both updated): Windows 10 v2004 / v20H2

# Issue:
The boxstarter script gives DNS resolution errors even though the virtual machine has NAT connectivity and is making DNS queries without issue. 

# Logs:

[chocolatey.log](https://github.com/fireeye/flare-vm/files/6359605/chocolatey.log)

```C:\Windows\system32>Call PowerShell -NoProfile -ExecutionPolicy bypass -command "Import-Module 'C:\ProgramData\boxstarter\Boxstarter.Bootstrapper\boxstarter.bootstrapper.psd1';Invoke-Boxstarter -RebootOk -NoPassword:$False"
Boxstarter Version 2.13.0
(c) 2018 Chocolatey Software, Inc, 2012 - 2018 Matt Wrock. https://boxstarter.org

Boxstarter: Disabling Automatic Updates from Windows Update
++ Boxstarter starting Calling Chocolatey to install commandovm.win10.installer.fireeye. This may take several minutes to complete...
Installing the following packages:
commandovm.win10.installer.fireeye
By installing you accept licenses for the packages.
[NuGet] An error occurred while loading packages from 'https://www.myget.org/F/fireeye/api/v2': The remote name could not be resolved: 'www.myget.org'
[NuGet] An error occurred while loading packages from 'https://chocolatey.org/api/v2': The remote name could not be resolved: 'chocolatey.org'
commandovm.win10.installer.fireeye not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "C:\ProgramData\boxstarter\BuildPackages;https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2"

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - commandovm.win10.installer.fireeye - commandovm.win10.installer.fireeye not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "C:\ProgramData\boxstarter\BuildPackages;https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2"
Chocolatey : Chocolatey reported an unsuccessful exit code of 1. See
C:\Users\root\AppData\Local\Boxstarter\boxstarter.log for details.
At C:\ProgramData\boxstarter\BoxStarter.Chocolatey\Invoke-ChocolateyBoxstarter.ps1:240 char:5
+     Chocolatey install $bootstrapPackage -source $source -force:$forc ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,chocolatey

Boxstarter: Error from Chocolatey:

Message        : Chocolatey reported an unsuccessful exit code of 1. See
                 C:\Users\root\AppData\Local\Boxstarter\boxstarter.log for details.
Data           : {}
InnerException :
TargetSite     :
StackTrace     :
HelpLink       :
Source         :
HResult        : -2146233087




++ Boxstarter finished Calling Chocolatey to install commandovm.win10.installer.fireeye. This may take several minutes to complete... 00:00:01.5794348
True
Boxstarter: Restore Automatic Updates from Windows Update
Boxstarter: Enabling UAC ```

**Comment by Antiseci** [comment]
> # 设置：
> * VMWare Fusion 12.1.1，NAT 网络
> * 尝试的操作系统（均已更新）：Windows 10 v2004 / v20H2
> 
> # 问题：
> 即使虚拟机具有 NAT 连接并且可以毫无问题地进行 DNS 查询，boxstarter 脚本也会出现 DNS 解析错误。
> 
> # 日志：
> [巧克力味的.log](https://github.com/fireeye/flare-vm/files/6359605/chocolatey.log)
> 
> ```
> Boxstarter Version 2.13.0
> (c) 2018 Chocolatey Software, Inc, 2012 - 2018 Matt Wrock. https://boxstarter.org
> 
> Boxstarter: Disabling Automatic Updates from Windows Update
> ++ Boxstarter starting Calling Chocolatey to install commandovm.win10.installer.fireeye. This may take several minutes to complete...
> Installing the following packages:
> commandovm.win10.installer.fireeye
> By installing you accept licenses for the packages.
> [NuGet] An error occurred while loading packages from 'https://www.myget.org/F/fireeye/api/v2': The remote name could not be resolved: 'www.myget.org'
> [NuGet] An error occurred while loading packages from 'https://chocolatey.org/api/v2': The remote name could not be resolved: 'chocolatey.org'
> commandovm.win10.installer.fireeye not installed. The package was not found with the source(s) listed.
>  If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
>  Version: ""
>  Source(s): "C:\ProgramData\boxstarter\BuildPackages;https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2"
> 
> Chocolatey installed 0/1 packages. 1 packages failed.
>  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
> 
> Failures
>  - commandovm.win10.installer.fireeye - commandovm.win10.installer.fireeye not installed. The package was not found with the source(s) listed.
>  If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
>  Version: ""
>  Source(s): "C:\ProgramData\boxstarter\BuildPackages;https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2"
> Chocolatey : Chocolatey reported an unsuccessful exit code of 1. See
> C:\Users\root\AppData\Local\Boxstarter\boxstarter.log for details.
> At C:\ProgramData\boxstarter\BoxStarter.Chocolatey\Invoke-ChocolateyBoxstarter.ps1:240 char:5
> +     Chocolatey install $bootstrapPackage -source $source -force:$forc ...
> +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,chocolatey
> 
> Boxstarter: Error from Chocolatey:
> 
> Message        : Chocolatey reported an unsuccessful exit code of 1. See
>                  C:\Users\root\AppData\Local\Boxstarter\boxstarter.log for details.
> Data           : {}
> InnerException :
> TargetSite     :
> StackTrace     :
> HelpLink       :
> Source         :
> HResult        : -2146233087
> 
> 
> 
> 
> ++ Boxstarter finished Calling Chocolatey to install commandovm.win10.installer.fireeye. This may take several minutes to complete... 00:00:01.5794348
> True
> Boxstarter: Restore Automatic Updates from Windows Update
> Boxstarter: Enabling UAC ```
> ```

How did you solve this problem

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
