### ISSUE TITLE
Install process loop stuck fails on vcbuildtools. 

### ISSUE THREAD

**Issue by CCCS-MA** [mandiant/flare-vm#362]
After following the instructions laid out, my install package just loops on an infinite basis. Currently trying to install on a Windows 10 Home VM. Appears to get stuck at "The install of vcbuildtools was not successful."

I only manage to get as far as cmder being installed. Then it looks like it installs python/a series of python packages but then it enters an continuing loop, restarts, attempts to install the same thing, etc.

**Comment by Flok2019** [comment]
I am experiencing the same issue. I already tried Windows 10 and Windows 7.

**Comment by rwt88** [comment]
I am also experiencing this issue on Windows 10

**Comment by rwt88** [comment]
```
WARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\vcbuildtools_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error.
ERROR: Running ["C:\Users\Malware\AppData\Local\Temp\vcbuildtools\2015.4\visualcppbuildtools_full.exe" /S ] was not successful. Exit code was '1603'. Exit code indicates the following: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\vcbuildtools_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error..
The upgrade of vcbuildtools was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\vcbuildtools\tools\chocolateyinstall.ps1'.
See log for details.
```
If this helps at all this is the warning and error

**Comment by MajorKitten** [comment]
Experiencing this issue on Windows 10 too

**Comment by Bob-The-User** [comment]
I downloaded the following and it fixed that particular issue: https://www.microsoft.com/en-us/download/details.aspx?id=48159

I then ran into issues with another package stringsifter. I had to manually install it and all of it's dependents.

**Comment by MalwareMechanic** [comment]
Hey all,

Thanks for bringing this to our attention. We've updated the `vcbuildtools.fireeye` package to depend on the [2017 VC build tools package](https://community.chocolatey.org/packages?q=visualstudio2017buildtools) and removed the `vcpython27` package from the installation list.

Please give the updates a whirl and let us know if the problem persists.
