### ISSUE TITLE
pdf-parser does not work with yara

### ISSUE THREAD

**Issue by scalpe1** [mandiant/flare-vm#370]
Using the -y option with pdf-parser results in error:
"option yara requires the YARA python module".

It seems however to be installed.

**Comment by RyanNgCT** [comment]
Having the same issue on both FlareVM (python 3.7.9), pdf-parser 0.7.4 (latest version) and kali linux (python 2.7).

**Windows**
![Screenshot 2021-06-16 092341](https://user-images.githubusercontent.com/48358569/122146229-3b8efc80-ce89-11eb-9cb4-3036320a87e7.png)

**Kali**
![Screenshot 2021-06-16 095420](https://user-images.githubusercontent.com/48358569/122146258-4ba6dc00-ce89-11eb-92ec-d78cb41f5556.png)

There doesn't seem to be an issues tab in the [creator's github repo](https://github.com/DidierStevens/DidierStevensSuite)

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
