### ISSUE TITLE
Install script breaks when username contains one or more spaces.

### ISSUE THREAD

**Issue by CriticalSteffen** [mandiant/flare-vm#371]
There is only one user account I set up on the system: **Malware Analyst**

Meanwhile, it appears the script attempted to install as the **Malware** user, which doesn't exist:

![wrong_user](https://user-images.githubusercontent.com/78458218/117186168-2f028900-ada0-11eb-8e95-24431c425912.png)

As you can see, these files were extracted into the `c:\users\Malware` directory instead of the `c:\users\Malware Analyst` directory. This may be the cause of the problem.

This appears to be caused by the fact that the username contains a space.

As a result, the installation failed.

_Originally posted by @CriticalSteffen in https://github.com/fireeye/flare-vm/issues/364#issuecomment-832887372_

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
