### ISSUE TITLE
Checking Missing Files

### ISSUE THREAD

**Issue by bmmojo** [mandiant/flare-vm#372]
Hey guys

I was wondering if you guys have a command where it tells you which programs are not installed?
My installation of FLARE VM was successful but a few programs were not installed. 
Error:  "The package was not found with the source (S) listed."

**Comment by MalwareMechanic** [comment]
Hey @bmmojo,

At the moment we don't have a nice script that does this, but you can check the location below:
- %PROGRAMDATA%\Chocolatey\lib-bad

If you see directories here, they correspond to packages that Chocolatey knows failed.

I like the idea of support scripts, perhaps we can look into creating some in the near future.

**Comment by bmmojo** [comment]
Yeah that'd be great! I also want to mention that Ollydbg, Ollydbg2, and OllyDump are not installed through the script. I had to go the website and install them.

**Comment by bmmojo** [comment]
@MalwareMechanic 

Hey! So I had to reinstall my FlareVM onto Hyper-V. This time I wrote down all the programs that didn't get installed. Hopefully, this is helpful and provides value for the next update to FlareVM.

**Hypervisor:** Hyper-V
**OS:** Windows 10 Pro x64 (this is not the _Windows 10 w/ Microsoft Edge_ or _Windows 10 Dev Env_)
**Installing Additional Packages:** command used "_cinst_". The only packages this worked on was "_ollydbg_." I did not try on the Python2.7 modules because I wasn't sure how to do it.

**Debuggers:** 

Ollydbg
Ollydbg
Ollydump
Ollydumpex
pykd

**Decompilers:**

RetDec

**Developer Tools:**

VC Build Tools (I think this is in, but I'm just including it cause I'm not sure)

**Disassemblers:**

IDA Free (5.0)

**Pentest:**

Windows Binaries from Kali Linux

**Web Application:**

Burpsuite Free Edition

**Utilities:**

Unxutils
Cyberchef
Uniextract2

**Python, Modules, Tools:**

**Python 2.7:**
binwalk
pycrypto
yara-python
mkyara

**Comment by MalwareMechanic** [comment]
@bmmojo Thanks for reporting!

I've never tested with Hyper-V myself (so you're in untested territory). Interesting, these should install... I wonder if it's something with Windows Defender eating the binaries up?

I'm in the process of revamping the packages and hope to get a larger update out in Q3 of this year, so stay tuned :D

Apologies if it's neglected slightly while it's under development.

**Comment by bmmojo** [comment]
@MalwareMechanic 
Hyper-V so far is great compared to the problems I had with VirtualBox (i.e. slowness). So if you guys test it that would be awesome!

It is possible that _Windows Defender_ is eating the binaries... when I started installing _FlareVM_, I am able to turn off "_Real-Time Protection_" in _Windows Security_ in that session. However, once the system restarts "_Real-Time Protection_" will turn back on. I was also trying to disable "_Windows Defender Advanced Threat Protection Service_" in "_services.msc_" (_Run as Administrator_) thinking that it would resolve the issue but Windows wouldn't allow me to do that. 

Also to show this is the type of errors I'll get when I run "_cinst_" on the packages I listed earlier.

```
`By installing you accept licenses for the packages.
ollydbg2 not installed. The package was not found with the source(s) listed.
 Source(s): 'https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - ollydbg2 - ollydbg2 not installed. The package was not found with the source(s) listed.
 Source(s): 'https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.`

```

Hopefully that helps! I'm looking forward to the Q3 update!

**Comment by MalwareMechanic** [comment]
@bmmojo Ah for the `cinst` issues, I believe the package name is `ollydbg2.flare`. We have a slight discrepancy between `.flare` and `.fireeye` packages, but I'm attempting to unify them going forward.

For the failed packages listed in `%PROGRAMDATA%\Chocolatey\lib-bad`, use the full directory name as the package name. For example:

`cinst ollydbg2.flare`

**Comment by bmmojo** [comment]
@MalwareMechanic 

So `cinst` the failed packages listed in `%PROGRAMDATA%\Chocolatey\lib-bad` gives me a error like this. `DotNet3.5` gave me a much longer error. `cinst ollydbg2.flare` worked though.
```
 PS C:\Windows\system32 > cinst x64dbg.py.flare
Chocolatey v0.10.15
Installing the following packages:
x64dbg.py.flare
By installing you accept licenses for the packages.
Progress: Downloading x64dbg.py.flare 1.0.54... 100%

x64dbg.py.flare v1.0.54
x64dbg.py.flare package files install completed. Performing other installation steps.
Attempt to get headers for https://ci.appveyor.com/api/buildjobs/g8562v6jb6udimi2/artifacts/release.zip failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://ci.appveyor.com/api/buildjobs/g8562v6jb6udimi2/artifacts/release.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading x64dbg.py
  from 'https://ci.appveyor.com/api/buildjobs/g8562v6jb6udimi2/artifacts/release.zip'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://ci.appveyor.com/api/buildjobs/g8562v6jb6udimi2/artifacts/release.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The install of x64dbg.py.flare was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\x64dbg.py.flare\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - x64dbg.py.flare (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\x64dbg.py.flare\tools\chocolateyinstall.ps1'.
 See log for details.
```

**Comment by nhatbv2** [comment]
The link "https://ci.appveyor.com/api/buildjobs/g8562v6jb6udimi2/artifacts/release.zip" is no longer available.

**Comment by bmmojo** [comment]
@nhatbv2 Yeah I saw that when I tried installing x64dbg.py.flare

@MalwareMechanic 

Since, I'm creating another FlareVM. I figure I update on what is still missing and what can be manually installed by using `cinst`

**Not there or partially there:**

**Debuggers:** 
Ollydump
- I am unsure if Ollydump = oledump.fireeye

Ollydumpex
pykd

**Disassemblers:**
IDA Free (5.0)

**Office:**
- For these Python scripts I was able to find it on Didier Steven's [Github](https://github.com/DidierStevens/DidierStevensSuite) page but I don't know exactly how to install this and get it all working. It would be cool on the next update for FlareVM you could share how to do that! :) 

rtfdump.py
oledump.py
msoffcrypto-crack.py

**Web Application:**
Burpsuite Free Edition

**Python, Modules, Tools:**

**Python 2.7:**
binwalk
vivisect
mkyara
yara-python
pycryptodome 
- This is partially there... it only has pycryptodome-3.10.1.dist-info folder with no .py files in it. I've tried `pip install pycryptodome`, but I'm missing files.

**Python 3.7:**
yara-python
- This is partially there... it only has yara_python-4.1.0.dist-info folder with no .py files in it. I've tried `pip install yara-python`, but I'm missing files.
pycryptodome
- This is partially there... it only has pycryptodome-3.10.1.dist-info folder with no .py files in it. I've tried `pip install pycryptodome`, but I'm missing files.

**Manual installation:**
cinst ollydbg
cinst ollydbg2.flare
cinst retdec.flare
cinst radare2
cinst kali.fireye
cinst hashmyfiles-
cinst floss
cinst map.flare
pip install vivisect

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
