### ISSUE TITLE
Issue installing nodejs

### ISSUE THREAD

**Issue by Soren17** [mandiant/flare-vm#377]
cup nodejs
Chocolatey v0.10.15
Upgrading the following packages:
nodejs
By upgrading you accept licenses for the packages.

You have nodejs v13.14.0 installed. Version 16.5.0 is available based on your source(s).
nodejs not upgraded. An error occurred during installation:
 Updating 'nodejs 13.14.0' to 'nodejs 16.5.0' failed. Unable to find a version of 'malware-jail.fireeye' that is compatible with 'nodejs 16.5.0'.
nodejs package files upgrade completed. Performing other installation steps.
The upgrade of nodejs was NOT successful.
nodejs not upgraded. An error occurred during installation:
 Updating 'nodejs 13.14.0' to 'nodejs 16.5.0' failed. Unable to find a version of 'malware-jail.fireeye' that is compatible with 'nodejs 16.5.0'.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - nodejs (exited 1) - nodejs not upgraded. An error occurred during installation:
 Updating 'nodejs 13.14.0' to 'nodejs 16.5.0' failed. Unable to find a version of 'malware-jail.fireeye' that is compatible with 'nodejs 16.5.0'.

**Comment by N1c0sA** [comment]
Same issue here
Failures
 - nodejs.install (exited 1) - nodejs.install not upgraded. An error occurred during installation:
 Updating 'nodejs.install 13.14.0' to 'nodejs.install 16.9.1' failed. Unable to find a version of 'nodejs' that is compatible with 'nodejs.install 16.9.1'.
 - nodejs (exited 1) - nodejs not upgraded. An error occurred during installation:
 Updating 'nodejs 13.14.0' to 'nodejs 16.9.1' failed. Unable to find a version of 'malware-jail.fireeye' that is compatible with 'nodejs 16.9.1'.

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
