### ISSUE TITLE
Failed Choco Installs Small List Presented Here

### ISSUE THREAD

**Issue by shaneholloman** [mandiant/flare-vm#378]
This installation was on a fresh Win10 Dev Hyper-V Build  `Windows 10 Enterprise Evaluation 21H1 (10.0.20348.0)`  
From here: <https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/>

Pre-installed on that VM outta the box was:
- This evaluation virtual machine includes:
- Windows 10 Enterprise Evaluation 21H1 (10.0.20348.0)
- Windows 10 SDK, version 2104 (10.0.20348.0)
- Visual Studio 2019 (latest as of 7/08/21) with the UWP, .NET desktop
- Azure workflows enabled and also includes the Windows Template Studio extension
- Visual Studio Code (latest as of 7/08/21)
- Windows Subsystem for Linux enabled with Ubuntu installed
- Developer mode enabled

## `Get-WmiObject` Complaint Solve

I initially used PowerShell 7
Using Windows PowerShell instead helped with the `Get-WmiObject` complaint

## ` Get-Service WinDefend` Fail

I could not solve

## Was able to manually install

- choco install radare2 -y
- choco install hashmyfiles -y
- choco install x64dbg.portable -y # only portable available

## Could not find this package

- pmalabs

## Failed Installs

- 2021/07/22 21:11:13 [pmalabs.flare] chocolateyinstall.ps1 [+] ERROR : Failed to install pmalabs.flare

- 2021/07/22 21:11:01 [hashmyfiles.flare] chocolateyinstall.ps1 [+] ERROR : Failed to install hashmyfiles.flare

- 2021/07/22 21:10:49 [radare2.flare] chocolateyinstall.ps1 [+] ERROR : Failed to install radare2.flare

- 2021/07/22 21:10:39 [x64dbg.py.flare] chocolateyinstall.ps1 [+] ERROR : Failed to install x64dbg.py.flare

## Failed Actions

```powershell
Get-WmiObject: C:\ProgramData\boxstarter\Boxstarter.Common\Get-IsRemote.ps1:25
Line |
  25 |     $parent = (Get-WmiObject -Class Win32_Process -Filter "ProcessID=$ …
     |                ~~~~~~~~~~~~~
     | The term 'Get-WmiObject' is not recognized as a name of a cmdlet, function, script file, or executable
     | program. Check the spelling of the name, or if a path was included, verify that the path is correct
     | and try again
```

```powershell
Stop-Service: C:\Users\User\github\flare-vm\install.ps1:316
Line |
 316 |    Get-Service WinDefend | Stop-Service -Force
     |                            ~~~~~~~~~~~~~~~~~~~
     | Service 'Microsoft Defender Antivirus Service (WinDefend)' cannot be stopped due to the following
     | error: Cannot open 'WinDefend' service on computer '.'.
```

```powershell
Set-ItemProperty: C:\Users\User\github\flare-vm\install.ps1:317
Line |
 317 |    Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\services\Win …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Attempted to perform an unauthorized operation.
```

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
