### ISSUE TITLE
Install on Windows 10 x64 fails for radare2, x64dbg.py, MAP, and hashmyfiles

### ISSUE THREAD

**Issue by makaiss0n** [mandiant/flare-vm#380]
In case of x64dbgpy, it is clear that URL is dead - one can find potential alternative here -> https://github.com/x64dbg/x64dbgpy/releases/tag/b275005

In case of radare2 issue is very simple - x64 link has HTTPS for the source URL (and certificate has expired). For x32 it is HTTP from the get go.

In case of MAP and hashmyfiles the issue is change in sha256.

**Comment by cccs-js** [comment]
Same thing on Windows 7

**Comment by cy83rs30rd** [comment]
Same issues on Windows 7 x64
