### ISSUE TITLE
Unable to install on Windows 10 

### ISSUE THREAD

**Issue by MMULLINIX1** [mandiant/flare-vm#382]
ERROR: The term 'Set-TaskbarOptions' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
The install of tmpabb4.tmp was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\tmpABB4.tmp\tools\ChocolateyInstall.ps1'.
 See log for details.

[boxstarter.log](https://github.com/fireeye/flare-vm/files/7042186/boxstarter.log)

**Comment by MMULLINIX1** [comment]
Forgot to add, Windows 10, v21H1, 64bit

**Comment by scsdev-cyber** [comment]
I've having issue windows 10 home version, seems not supported.

**Comment by Pernat1y** [comment]
It replaced with 'Set-BoxstarterTaskbarOptions' ( see https://boxstarter.org/WinConfig )

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
