### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by HercFila** [mandiant/flare-vm#384]
I used to install it normally but now on windows 10 ver 21h1 can't and it gives me these errors:

[2021-09-24T17:44:52.6225642-07:00:::PID 3996] Boxstarter: restoring current directory location to C:\Windows\system32
VERBOSE: Boxstarter: restoring current directory location to C:\Windows\system32
[2021-09-24T17:44:52.6225642-07:00:::PID 3996] Boxstarter: Exit Code: 1
VERBOSE: Boxstarter: Exit Code: 1
Chocolatey reported an unsuccessful exit code of 1. See C:\Users\Malware Lab\AppData\Local\Boxstarter\boxstarter.log for details.
[2021-09-24T17:44:52.6225642-07:00:::PID 3996] Boxstarter: There was an error calling Chocolatey
VERBOSE: Boxstarter: There was an error calling Chocolatey
[2021-09-24T17:44:52.6225642-07:00:::PID 3996] Boxstarter: Error from Chocolatey: 

Message        : Chocolatey reported an unsuccessful exit code of 1. See C:\Users\Malware Lab\AppData\Local\Boxstarter\

Failures
 - flarevm.win10.config.fireeye Lab\AppData\Local\ChocoCache - flarevm.win10.config.fireeye Lab\AppData\Local\ChocoCache not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "C:\ProgramData\boxstarter\BuildPackages;https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2"

And series of these errors through the installation:

![image](https://user-images.githubusercontent.com/91135227/134752426-31681955-7373-4d3e-964a-dc597b14d153.png)

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
