### ISSUE TITLE
dnspy revived 6.1.9 released

### ISSUE THREAD

**Issue by cy83rs30rd** [mandiant/flare-vm#385]
Sounds like original dnSpy is no more has been revived and 6.1.9 is released:
https://github.com/dnSpyEx/dnSpy/releases/tag/v6.1.9

Love what you guys have done with FlareVM, keep up the good work!
Cheers!

**Comment by Maijin** [comment]
+1 on this 👍

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
