### ISSUE TITLE
Suggestion: Add Fibratus tool

### ISSUE THREAD

**Issue by rabbitstack** [mandiant/flare-vm#394]
Hi,

Would you find it beneficial adding [Fibratus](https://www.fibratus.io) in the list of available tools?
Fibratus is a tool for Windows kernel tracing and observability. It includes a powerful filter engine, the ability to generate capture files ala pcap, craft Python scriplets on top of kernel event stream, transport events to output sinks and much more.

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
