### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by PranavMare** [mandiant/flare-vm#395]
I accidently ran the install scripts from the website on my host OS instead of a VM. How do I uninstall and reverse the script?

**Comment by MalwareMechanic** [comment]
@PranavMare No guarantee's that this will uninstall everything, but here are a few steps below. This will be very tedious and likely messy.

> WARNING: I encourage you to back up your files prior to continuing and understand what each command does before running. This may make drastic changes to your host OS.

From an admin PowerShell prompt:

1. Run `choco uninstall flarevm.installer.flare` (or `choco uninstall flarevm.win10.installer.fireeye` for which one you installed) to uninstall the packages. However, this will not uninstall the dependencies of each package.
2. To uninstall any remaining packages (such as dependencies), you can attempt to run `choco uninstall all`
    - See: https://docs.chocolatey.org/en-us/choco/commands/uninstall
3. Uninstall Chocolatey itself by following: https://community.chocolatey.org/courses/installation/uninstalling
4. Uninstall Boxstarter by following the instructions at the bottom of: https://boxstarter.org/installboxstarter
5. Manually undo various configuration settings changed during FLARE-VM installation by reading through various installation scripts:
    - https://github.com/mandiant/flare-vm/tree/master/flarevm.win10.preconfig.fireeye/tools
    - https://github.com/mandiant/flare-vm/blob/master/flarevm.win10.config.fireeye/tools/chocolateyinstall.ps1
    - https://github.com/mandiant/flare-vm/blob/master/flarevm.config.flare/tools/chocolateyinstall.ps1
    - https://github.com/mandiant/flare-vm/blob/master/flarevm.installer.flare/tools/chocolateyinstall.ps1
    - https://github.com/mandiant/flare-vm/blob/master/flarevm.win10.installer.fireeye/tools/chocolateyinstall.ps1
6. Look through `Program and Features` and manually uninstall anything left over.

We'll update the installer scripts in Q2 to have a VM check so this doesn't happen in the future. We had planned on updates in Q1, but had to push back to Q2. Good luck!

**Comment by TudorDasc** [comment]
Hello, I have the same problem (I installed the flare VM on the host OS) and I tried almost everything from the above, but it did not work. The problem that I have, is that there is another user created from the installation of the flare VM and it does not let me log in original user, telling me that the is a network problem. 
Do you have any idea of what I could do? (like reinstalling the windows or anything that could help me?)

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
