### ISSUE TITLE
How to check for the following file attributes?

### ISSUE THREAD

**Issue by flamecopper** [mandiant/flare-vm#396]
Hi there,
What tools do I used to check for the following file attributes?

Is the file executable? -> peinfo
Is the file binary? -> Ok 
For which architecture (x86 or x86-64) is the binary compiled? -> exeinfo
Is the binary stripped of its symbol table? 
Can any useful strings be identified within the binary? -> strings
Is there a running process associated with this binary? -> processexplorer, procmon
What is the Secure Hash Algorithm (SHA) hash of the binary? -> exeinfo, peinfo
Is the hash a known malicious file hash? -> exeinfo, peinfo
What was the original programming language used? -> can be any
Can any useful function names be identified? -> IDA, X64 DBG, X32 DBG

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
