### ISSUE TITLE
Unable to install FLARE on WIN 10 - AppData\Local\ChocoCache not installed error

### ISSUE THREAD

**Issue by noadekel-DI** [mandiant/flare-vm#399]
Hi, 
I've been trying to install FLARE on several different builds of windows 10, but they all fail due to some problem with Boxstarter\Chocolately. Here's the some of the installation log (it's the same error for every package it tries to install):
`+ Boxstarter starting Calling Chocolatey to install capa.fireeye. This may take several minutes to complete...
+ Boxstarter starting Calling Chocolatey to install capa.fireeye. This may take several minutes to complete...
Upgrading the following packages:
capa.fireeye Dekel\AppData\Local\ChocoCache
By upgrading you accept licenses for the packages.
capa.fireeye Dekel\AppData\Local\ChocoCache is not installed. Installing...
capa.fireeye Dekel\AppData\Local\ChocoCache not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "C:\ProgramData\boxstarter\BuildPackages;https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2"

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - capa.fireeye Dekel\AppData\Local\ChocoCache - capa.fireeye Dekel\AppData\Local\ChocoCache not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "C:\ProgramData\boxstarter\BuildPackages;https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2"
Chocolatey reported an unsuccessful exit code of 1. See C:\Users\Noa Dekel\AppData\Local\Boxstarter\boxstarter.log for details.
Boxstarter: Error from Chocolatey:

Message        : Chocolatey reported an unsuccessful exit code of 1. See C:\Users\Noa Dekel\AppData\Local\Boxstarter\boxstarter.log for details.
Data           : {}
InnerException :
TargetSite     :
StackTrace     :
HelpLink       :
Source         :
HResult        : -2146233087

Boxstarter: Error from Chocolatey:

Message        : Chocolatey reported an unsuccessful exit code of 1. See C:\Users\Noa Dekel\AppData\Local\Boxstarter\boxstarter.log for details.
Data           : {}
InnerException :
TargetSite     :
StackTrace     :
HelpLink       :
Source         :
HResult        : -2146233087

+ Boxstarter finished Calling Chocolatey to install capa.fireeye. This may take several minutes to complete... 00:00:00.4674275
+ Boxstarter finished Calling Chocolatey to install capa.fireeye. This may take several minutes to complete... 00:00:00.4674275
+ Boxstarter starting Calling Chocolatey to install Dekel\AppData\Local\ChocoCache. This may take several minutes to complete...
+ Boxstarter starting Calling Chocolatey to install Dekel\AppData\Local\ChocoCache. This may take several minutes to complete...
Upgrading the following packages:
capa.fireeye Dekel\AppData\Local\ChocoCache
By upgrading you accept licenses for the packages.
capa.fireeye Dekel\AppData\Local\ChocoCache is not installed. Installing...
capa.fireeye Dekel\AppData\Local\ChocoCache not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "C:\ProgramData\boxstarter\BuildPackages;https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2"

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - capa.fireeye Dekel\AppData\Local\ChocoCache - capa.fireeye Dekel\AppData\Local\ChocoCache not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "C:\ProgramData\boxstarter\BuildPackages;https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2"
Chocolatey reported an unsuccessful exit code of 1. See C:\Users\Noa Dekel\AppData\Local\Boxstarter\boxstarter.log for details.
Boxstarter: Error from Chocolatey:

Message        : Chocolatey reported an unsuccessful exit code of 1. See C:\Users\Noa Dekel\AppData\Local\Boxstarter\boxstarter.log for details.
Data           : {}
InnerException :
TargetSite     :
StackTrace     :
HelpLink       :
Source         :
HResult        : -2146233087`

**Comment by Spart4nious** [comment]
I had the same problem, the process failed every time at different step so I supposed an "environmental" issue. The problem in my case was related to insufficient resources, I had 2 GB RAM. After upgrading the VM to 4 GB the installation completed successfully.

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.

**Comment by kevinkeo4** [comment]
> Thank you for your feedback! We've been working on major updates to FLARE VM over the last year. The now revamped FLARE VM has just been released and will make the project more open and maintainable. Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.
> 
> If this problem still persists with the new installation, please report:
> 
>     * new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
> 
>     * ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues
> 
> 
> Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.

I recently tried this and i am getting the boxstarter/chocolatey error message
![image (3)](https://github.com/mandiant/flare-vm/assets/103232965/e7852635-2482-4c45-b5e6-dc881ff14b40)

**Comment by mr-tz** [comment]
I'd recommend to open a new issue for your error.

**Comment by kevinkeo4** [comment]
> I'd recommend to open a new issue for your error.

Yeah i just did about 3 minutes ago. thanks for letting me know.
