### ISSUE TITLE
Link to Windows 10 development environment VM

### ISSUE THREAD

**Issue by threat-punter** [mandiant/flare-vm#400]
Just a heads up, the link in the readme for this repo links to a Windows 11 development environment VM now. I guess Microsoft swapped out the Windows 10 VM that you linked to.

https://github.com/mandiant/flare-vm/blob/d13739f43d17d18b75bdff3c66fa121c541e1eed/README.md?plain=1#L29

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
