### ISSUE TITLE
Summary of all Issues

### ISSUE THREAD

**Issue by SeaLi-oN** [mandiant/flare-vm#414]
### FlareVM is outdated and needs to be redeveloped
I mean the VM is a fantastic idea and concept when it works 
sadly there are a lot of issues with it, like tools that are outdated and not installed properly
maybe a good way to fix it is by rebuilding it with the help of the community, i am sure many people would like to help
!!! 
Thanks and sorry for the Harsh feedback,

**Comment by gg-jim** [comment]
I really hope this project isn't dead

**Comment by seanthegeek** [comment]
Good news everyone! The FLARE team is actively working on overhauling FLARE-VM behind the scenes.

https://twitter.com/MalwareMechanic/status/1562952356576104448?s=20&t=LaqNQnBHyantLSea-eILTA

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
