### ISSUE TITLE
Installation Error - myget.org is Down

### ISSUE THREAD

**Issue by beersploit** [mandiant/flare-vm#417]
Constantly getting "Error retrieving packages from source https://www.myget.org/F/fireeye/api/v2: Unable to connect to the remote server". 
<img width="611" alt="image" src="https://user-images.githubusercontent.com/51427622/188214822-d9ab0d79-b6c9-4204-af90-b9be07ded7d5.png">

Looks like host is down from more than a day now:
https://www.isitdownrightnow.com/myget.org.html

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
