### ISSUE TITLE
Please Mark as Deprecated:  Over 6 Hours and No Success Installing flare-vm

### ISSUE THREAD

**Issue by gladiola** [mandiant/flare-vm#420]
I ask that you somehow place a warning on the README of this repo stating that many of the packages are out-of-date and cannot be installed.

I was referred to this repo by an EdX course ("Malware Analysis and Assembly Language Introduction ") which suggested that running this install script in a Win10 VM could be done in 30 minutes.  Over six hours later, I still see cascading errors.  I notice that some files require python2.  I have given up on these programs.  I feel like other people deserve a prominent warning before investing time in attempting to install this code.

Considering the age of the repo and the time since the last install, we would have appreciated a deprecation notice on the front page of this repo.  Please consider warning other users of the inoperable state of the install script.  We beg you.  Thanks.

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
