### ISSUE TITLE
Installation is not successful

### ISSUE THREAD

**Issue by AmirDey** [mandiant/flare-vm#422]
Hi, I can't install both with the ps and directly through the package, I don't get any errors at all.  what could be the problem?

**Comment by dsdrifter** [comment]
Hello! I tried to install the flare version 3.0 on virtualbox https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ using the link aforementioned and I'm only getting: "Not physical memory is available at the location required for the window manager. The system cannot continue." Not sure if it helps but I'm using virtualbox 7.0.4. Any idea on how to fix this?

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
