### ISSUE TITLE
Not opening on VirtualBox

### ISSUE THREAD

**Issue by dsdrifter** [mandiant/flare-vm#424]
Hello! I tried to install the flare version 3.0 on virtualbox https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ using the link aforementioned and I'm only getting: "Not physical memory is available at the location required for the window manager. The system cannot continue." Not sure if it helps but I'm using virtualbox 7.0.4. Any idea on how to fix this?

**Comment by MalwareMechanic** [comment]
Hey there,

We're in the works of finishing up a new version. But if I had to guess, you likely require more memory on your VM to perform the installation. Note: many packages are currently broken -- my advice would be to hold off until the new version is released. You may preview the release at: https://github.com/mandiant/flare-vm/tree/update_installer; however, the documentation still needs updating.

Hope that helps!

**Comment by dsdrifter** [comment]
Thanks for the help!
