### ISSUE TITLE
install.ps script does not install in my machine

### ISSUE THREAD

**Issue by guyhacker** [mandiant/flare-vm#429]
<img width="813" alt="Flare" src="https://user-images.githubusercontent.com/12577261/206062292-d1782b6d-cebb-4a79-b9c4-49f828973d5a.PNG">

### Description

The installation script does not run properly in Windows 10

### Steps to Reproduce

**Expected behavior:**

**Actual behavior:**

**Comment by MalwareMechanic** [comment]
Hey @guyhacker, thanks for reporting. Can you please let us know some additional information about your system to help us triage the issue. Information such as the below would be helpful:
- Host OS and virtualization software
- VM OS version and service pack
- VM OS ram and HDD space / usage
- VM PowerShell version
- VM Chocolatey version (if any)
- VM Boxstarter version (if any)

**Comment by mr-tz** [comment]
I think we need to add a `Test-Path` or similar here (and potentially at other places):
https://github.com/mandiant/flare-vm/blob/af1b9e096eb99fe13ba75038d3816d6eeeb724d5/install.ps1#L107

**Comment by MalwareMechanic** [comment]
Thanks for reporting @guyhacker 👍

**Comment by guyhacker** [comment]
![box](https://user-images.githubusercontent.com/12577261/206267473-779d0403-d2ac-4080-b861-1bd98b96f352.png)

**Comment by mr-tz** [comment]
Looks like an TLS error here. What VM OS version and service pack are you running?

**Comment by guyhacker** [comment]
I am running Windows 10 in a Vmware 15,

**Comment by mr-tz** [comment]
Great, glad it works. Happy reversing!

**Comment by guyhacker** [comment]
![image](https://user-images.githubusercontent.com/12577261/206501509-57d4374c-3a5e-44bb-8faa-7874d787e328.png)
