### ISSUE TITLE
[Question] FLARE-VM AMI?

### ISSUE THREAD

**Issue by HuskyHacks** [mandiant/flare-vm#436]
I wanted to throw this out there to gauge interest. I'm developing the cloud lab lecture material for PMAT and part of the setup is to have the student create their own FLARE-VM AMI and use Terraform to provision and tear down their malware analysis lab.

That got me thinking - is there any interest in maintaining an official FLARE-VM AMI that's publically available on the AMI catalog?

**Comment by MalwareMechanic** [comment]
Hmm interesting idea! I'd be interested in a GCP option 😄 Do you have any experience in that?

**Comment by HuskyHacks** [comment]
I don't have any experience with GCP, unfortunately.

I've created a FLARE-VM AMI and made it publically available if anyone wants to check it out for evaluation purposes. It's built on Windows Server 2022 and seems to work great! It's a t2.medium so it costs about $0.04 USD/hour to run the instance and probably about $3/month to maintain the AMI.

ami-0fa27ee2696dde5c9

![image](https://user-images.githubusercontent.com/57866415/214312768-8e7f5674-edf5-4544-8168-457ca48ce3ab.png)

**Comment by sshakoor98** [comment]
Hey HuskyHacks, which AWS region is that being hosted on? I can't find it on Asia Pacific.

**Comment by HuskyHacks** [comment]
@sshakoor98 the AMI is on us-east-1. You have to host AMIs by region and it would get a little expensive to host across the different regions, so I'm keeping it to us-east-1 for now.
