### ISSUE TITLE
Getting Error when downloading the install.ps1 file

### ISSUE THREAD

**Issue by Niyanth-guru** [mandiant/flare-vm#439]
I am trying to download the install.ps1 from PowerShell console(in admin privilege). I am getting this particular error(which I have included a screenshot of below). I tried googling to find out the error but couldn't find anything. Could you please help me with this issue?
![issue-download](https://user-images.githubusercontent.com/58947833/220657715-8a9c9f3e-a43b-4d42-b22f-f94ee850899e.PNG)

**Comment by mr-tz** [comment]
Can you check Internet access (in your VM and from the console)?
Alternatively, can you download the file from the URL and execute in two steps?

**Comment by dhruval** [comment]
Correct Niyanth, most of the download links are not wokring and it makes installation manual. Please fix the install.ps1, flarevm.png available on gitcontent. Thanks.

**Comment by mr-tz** [comment]
Do you mean the links in the doc and scripts are broken? If so, which ones are failing for you?

**Comment by thomasgeens** [comment]
Can confirm that I am having NO issues with the download link from the docs. So running the command ´(New-Object net.webclient).DownloadFile('https://raw.githubusercontent.com/mandiant/flare-vm/main/install.ps1',"$([Environment]::GetFolderPath("Desktop"))\install.ps1")´ works perfect.

@dhruval , maybe try to verify if you are not running into TLS version issues?
´iwr https://raw.githubusercontent.com/mandiant/flare-vm/main/install.ps1´

´[System.Net.ServicePointManager]::SecurityProtocol´

**Comment by Niyanth-guru** [comment]
> Can you check Internet access (in your VM and from the console)? Alternatively, can you download the file from the URL and execute in two steps?

So I gave your technique a try, and I managed to obtain the install.ps1 file. As it can be seen from the snap below
![proof of install ps1 download](https://user-images.githubusercontent.com/58947833/221569062-54f7c8da-df4d-4061-af45-e2d7488d6998.PNG)

However, I am not able to run the software and receiving an error message. Another issue is that I can't make out a single word of the error message. Here is the snap of the issue.
![next_issue-download](https://user-images.githubusercontent.com/58947833/221570145-7e69551a-e250-4940-8460-3dd0bcad6b8d.PNG)

The internet links are also in good condition. I've left the VM in NAT mode for the time being, and I can reach the internet just fine.

**Comment by Kashyap-source** [comment]
Hello, even I faced the same issue which Niyanth faced while running the script, I checked the script and found no error with it, then while following the given steps in set-Execution policy instead of Y (yes), I did A (Yes to All) and the script run perfectly and all the tools were installed.

**Comment by thomasgeens** [comment]
Maybe verify if the encoding of the files is correct,it should probably be UTF or ANSI. The errors you are getting often occur because of wrong encoding formats such as Unicode etc.
Maybe you manually copied some content somewhere and saved with wrong encoding, or could even be saved wrong on Githun, or a wrong preset in your own git configuration.

**Comment by mr-tz** [comment]
Thanks for the additional input @Kashyap-source and @thomasgeens!
@Niyanth-guru, please reopen this issue, if you still have difficulties with this.
