### ISSUE TITLE
flarevm.installer.vm not installed. The package was not found with the source(s) listed.

### ISSUE THREAD

**Issue by NomanProdhan** [mandiant/flare-vm#445]
I was trying to setup FlareVM on my Windows 10 Pro (19045) and I got the error``` flarevm.installer.vm not installed. The package was not found with the source(s) listed.``` 
I checked the logs and noticed that this is happening for my username! My username was "Noman Prodhan" and when the FlareVM installer was trying to install tools or required packages it was only using "Noman" in path like this ``` C:\Users\Noman``` but the path should be ``` C:\Users\Noman Prodhan```

So I tried a new VM with the username "Noman" and it's working fine without any problem.
I think there is a problem with the installer that ignores any text after the space in our username. 
I know we don't often use spaces in our usernames. But still, since Windows allows spaces in usernames, some users may use it.

Please check the log file.
[chocolatey.log](https://github.com/mandiant/flare-vm/files/11143064/chocolatey.log)

**Comment by mr-tz** [comment]
Yeah, correct. Glad you figured it out. See the related issue #371.
We had an issue for testing this in https://github.com/mandiant/VM-Packages/issues/29, but decided it's not worth the extra effort.

Do you think we should change the warning in the install doc to make this clearer?

**Comment by NomanProdhan** [comment]
Hi @mr-tz 
Looks like I missed that warning in the installation doc. I think the warning is good enough, it's my mistake I missed it.

**Comment by mr-tz** [comment]
All good. Thanks!
