### ISSUE TITLE
vm packages

### ISSUE THREAD

**Issue by slava-godman** [mandiant/flare-vm#446]
sysinternals.vm
pestudio.vm
this 2 are failed to install ,I even delete my machine and put 200gb storage 

Failures
 - sysinternals.vm (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\sysinternals.vm\tools\chocolateyinstall.ps1'.
 See log for details.
 - sysinternals (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\sysinternals\tools\chocolateyInstall.ps1'.
 See log for details.

sysinternals.vm package files install completed. Performing other installation steps.
2023/04/13 01:02:15 [sysinternals.vm] vm.common.psm1 [+] ERROR : [ERR] Cannot find path 'C:\ProgramData\chocolatey\lib\sysinternals\tools' because it does not exist.
At C:\ProgramData\chocolatey\lib\sysinternals.vm\tools\chocolateyinstall.ps1:16 char:19
+ ... coToolDir = Join-Path ${Env:ChocolateyInstall} 'lib\sysinternals\tool ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERROR: Cannot find path 'C:\ProgramData\chocolatey\lib\sysinternals\tools' because it does not exist.
The install of sysinternals.vm was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\sysinternals.vm\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/2 packages. 2 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

**Comment by mr-tz** [comment]
We've just updated sysinternals (they don't have a version in their downloads, so it's hard for us to track). Please report future package fails in the https://github.com/mandiant/VM-Packages repo.
