### ISSUE TITLE
Error installing 7zip

### ISSUE THREAD

**Issue by josephtillman11** [mandiant/flare-vm#448]
```
[7zip-15-05.vm] vm.common.psm1 [+] ERROR : [ERR] The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://sourceforge.net/projects/sevenzip/files/7-Zip/15.05/7z1505-x64.exe/download'. Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."
At C:\ProgramData\chocolatey\helpers\functions\Get-WebFile.ps1:330 char:8
+        throw "The remote file either doesn't exist, is unauthorized,  ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://sourceforge.net/projects/sevenzip/files/7-Zip/15.05/7z1505-x64.exe/download'. Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."
The install of 7zip-15-05.vm was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\7zip-15-05.vm\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - 7zip-15-05.vm (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\7zip-15-05.vm\tools\chocolateyinstall.ps1'.
 See log for details.

```

------------------------------------------------------------------------------------

I can browse to https://sourceforge.net/projects/sevenzip/files/7-Zip/15.05/7z1505-x64.exe/download and download it just fine.

**Comment by Ana06** [comment]
The package installed correctly in the daily run few hours ago, so the url seems to work: https://github.com/mandiant/VM-Packages/actions/runs/4826706037

> I can browse to https://sourceforge.net/projects/sevenzip/files/7-Zip/15.05/7z1505-x64.exe/download and download it just fine.

Can you download it from the same VM you try to install the package? Have you tried to reinstall the package?

**Comment by nadrojisk** [comment]
I just started a new install of Flare on a fresh Windows 10 VM. For some reason every package is giving the same error. I can go out to the internet just fine on the VM as well. I did have to install an older version of chocolatey due to them removing `cinst`. I think that may have had something to do with it?

**Comment by mr-tz** [comment]
That may be the case. See the other issues for potential solution downgrading chocolatey or setting an alias.

Please reopen this or create a new issue if this still persists.
