### ISSUE TITLE
which is the best windows version to use flare-vm?lot's of conf pls help me out will I use win10 1809 or what ? best windows version and build to use with flare vm 

### ISSUE THREAD

**Issue by deadeyeroot** [mandiant/flare-vm#451]

**Comment by mr-tz** [comment]
Yes, as documented we've successfully tested the installation on Windows 10 1809 x64 and 20H2. Please open a new issue if you encounter any installation problems.

**Comment by deadeyeroot** [comment]
thank you so much i installed it 
no issue on win10 1809 R2
