### ISSUE TITLE
Check valid username in installer

### ISSUE THREAD

**Issue by elevateman** [mandiant/flare-vm#452]
Upon following this script:
Open a PowerShell prompt as administrator
Download the installation script [installer.ps1](https://raw.githubusercontent.com/mandiant/flare-vm/main/install.ps1) to your desktop
(New-Object net.webclient).DownloadFile('https://raw.githubusercontent.com/mandiant/flare-vm/main/install.ps1',"$([Environment]::GetFolderPath("Desktop"))\install.ps1")
Unblock the installation script by running:
Unblock-File .\install.ps1
Enable script execution by running:
Set-ExecutionPolicy Unrestricted
If you receive an error saying the execution policy is overridden by a policy defined at a more specific scope, you may need to pass a scope in via Set-ExecutionPolicy Unrestricted -Scope CurrentUser to view execution policies for all scopes, type Get-ExecutionPolicy -List
Finally, execute the installer script as follow:
.\install.ps1

I get the following error See Image

![Untitled](https://github.com/mandiant/flare-vm/assets/112668630/8be032bf-e85d-4662-a9b6-68fd8e1e2ab5)

**Comment by elevateman** [comment]
The solution is to build the windows 10 VM with a one word user name.  I kept making the fresh windows install with user name JOHN DOE instead of a single word user name.  This resolved the issue upon package install the paths wheee the package is installed is clear of blanks.

**Comment by HuskyHacks** [comment]
@Ana06 FYSA, adding this check in https://github.com/mandiant/flare-vm/pull/485

**Comment by mr-tz** [comment]
See #485, thanks @HuskyHacks!
