### ISSUE TITLE
unable to install .\install.ps1 script

### ISSUE THREAD

**Issue by jothiveldgl** [mandiant/flare-vm#455]
when i try to install this script in powershell admin (.\install .ps1) based on the given installation steps, I am getting the below error. I tried several times but its still persist. I am using windows 10

[+] Checking if script is running as administrator...
        [+] Running as administrator
[+] Checking if execution policy is unrestricted...
        [+] Execution policy is unrestricted
[+] Checking if Windows Defender Tamper Protection is disabled...
        [+] Tamper Protection is disabled
[+] Checking if Windows Defender service is disabled...
        [!] Please disable Windows Defender through Group Policy, reboot, and rerun installer
        [+] Hint: https://stackoverflow.com/questions/62174426/how-to-permanently-disable-windows-defender-real-time-protection-with-gpo
        [+] Hint: https://www.windowscentral.com/how-permanently-disable-windows-defender-windows-10
        [+] Hint: https://github.com/jeremybeaume/tools/blob/master/disable-defender.ps1
        [+] You are welcome to continue, but may experience errors downloading or installing packages
        [-] Do you still wish to proceed? (Y/N): Y
[+] Checking to make sure Operating System is compatible...
        [!] Windows version 19045 has not been tested. Tested versions: 17763, 19042
        [+] You are welcome to continue, but may experience errors downloading or installing packages
[-] Do you still wish to proceed? (Y/N): Y
[+] Checking if host has enough disk space...
        [+] Disk is larger than 60 GB
[-] Have you taken a VM snapshot to ensure you can revert to pre-installation state? (Y/N): Y
[+] Getting user credentials ...

Windows PowerShell credential request
Enter your credentials.
Password for user jothi: ******

[+] Installing Boxstarter...
Welcome to the Boxstarter Module installer!
Chocolatey installed, Installing Boxstarter Modules.
Invoke-Expression : The term 'cinst' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:55 char:9
+         Invoke-Expression $command
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (cinst:String) [Invoke-Expression], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.InvokeExpressionCommand

PS C:\Users\jothi\OneDrive\Desktop>

**Comment by PrettyBoyCosmo** [comment]
hey i'm getting this same issue too. i've followed all the appropriate instructions but am having no success

**Comment by DanAsBjorn** [comment]
Hey @jothiveldgl @PrettyBoyCosmo  to fix this problem I had to install chocolatey first and then install boxstarter with choco.

**Comment by DanAsBjorn** [comment]
https://github.com/mandiant/VM-Packages/issues/409

Seems to cover the issue

**Comment by DanAsBjorn** [comment]
run this command before the install script

``$env:chocolateyVersion = '1.4.0'`
`

**Comment by PrettyBoyCosmo** [comment]
didn't work for me, sorry :(

**Comment by DanAsBjorn** [comment]
@PrettyBoyCosmo you need to delete chocolatey first

**Comment by PrettyBoyCosmo** [comment]
ah gotchu, it seems to be working now. many thanks :D
i'll be sure to bother you if i run into any more issues haha 😉

**Comment by hetaofan** [comment]
Execuse me . I met this problem. can you help me solve it? how can I delete the chocolatey?

**Comment by hetaofan** [comment]
Thanks for your reply

Moritz ***@***.***> 于 2023年6月5日周一 20:21写道：

**Comment by Ana06** [comment]
Duplicate of https://github.com/mandiant/flare-vm/issues/456
