### ISSUE TITLE
cinst not able to read

### ISSUE THREAD

**Issue by wan-ilhami** [mandiant/flare-vm#457]
Hi, i tried many times installed the software. There are many ways i already did but still cant be installed. i already change many version of windows and the problem still same. can you help me?

![WhatsApp Image 2023-06-06 at 5 17 19 PM](https://github.com/mandiant/flare-vm/assets/68265380/ed5226ad-7d24-487b-acdb-f0ccb4df71bd)

**Comment by mr-tz** [comment]
Please see https://github.com/mandiant/flare-vm/issues/456.

**Comment by wan-ilhami** [comment]
where i can change the version of chocolatey? need to download separately? or just change on code? if in codes where is it?
