### ISSUE TITLE
Error "Cannot validate argument on parameter 'Argumentlist'. 

### ISSUE THREAD

**Issue by MnFrozenFish** [mandiant/flare-vm#461]
I am working on the installation on Windows 10 build 19045.  I did set $env:chocolateyVersion = '1.4.0'. 
 I also tried on Window11 MSEdge Evaluation and got exactly the same error.  Herewith the snapshot: 
![image](https://github.com/mandiant/flare-vm/assets/59742166/68b4d96e-b60f-483e-9995-4156aea2d5d4)

I saw on earlier posts that many have successfully installed flare vm on Windows 11 and I am curious what may have caused the issue above.  Thank you

**Comment by Ana06** [comment]
I think this error has been introduced in https://github.com/mandiant/VM-Packages/pull/429

**Comment by MnFrozenFish** [comment]
Thanks. I just tested installation of Flare VM on Win10 19042, it failed at the same point with the same error message

**Comment by Ana06** [comment]
I get the error as well when installing `flarevm.installer.vm` locally. It seems we are excluding `flarevm.installer.vm` from the tests (because it install other packages) so that's why the CI didn't catch the error.

**Comment by Ana06** [comment]
```
[2023-06-07T18:14:36.3212050+02:00:::PID 2916] Boxstarter: BoxstarterWrapper::Run(list  -r -y)...
[2023-06-07T18:14:36.3212050+02:00:::PID 2916] Boxstarter: restoring current directory location to C:\Windows\system32
[2023-06-07T18:14:36.3681205+02:00:::PID 2916] 2023/06/07 18:14:36 [flarevm.installer.vm] vm.common.psm1 [+] ERROR : [ERR] Cannot validate argument on parameter 'ArgumentList'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\ProgramData\boxstarter\Boxstarter.Common\Enter-DotNet4.ps1:38 char:9
+         Invoke-Command -ScriptBlock $ScriptBlock -argumentlist $Argum ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by MnFrozenFish** [comment]
> 
Are you suggesting that it is a prerequisite to have "flarevm.installer.vm" installed first before I can have any other packages installed?  Prior to the issue being fixed, is there anything I can do to proceed with installation at this point?

**Comment by mr-tz** [comment]
```
$installedPackages = choco list -r
$boxstarerInfo = $installedPackages | Select-String -Pattern "Boxstarter" | Out-String
```
results in:
```
jivkok.boxstarter1|1.0.0.4
Boxstarter.WindowsUpdate|1.1.0
Boxstarter.Azure|3.0.1
Boxstarter.TestRunner|3.0.1
boxstarter|3.0.1
boxstarter.bootstrapper|3.0.1
boxstarter.chocolatey|3.0.1
BoxStarter.Common|3.0.1
Boxstarter.HyperV|3.0.1
BoxStarter.WinConfig|3.0.1
```

likely not what we want

**Comment by mr-tz** [comment]
Best bet continues to be that the changed choco commands in https://github.com/mandiant/VM-Packages/pull/429/files are causing this. I can continue looking into this tomorrow.

**Comment by mr-tz** [comment]
Maybe @gep13 can chime in on the commands or if we need to do things differently now with the recent updates.

**Comment by gep13** [comment]
In Chocolatey v2.0.0 the default behaviour of `choco list` was changed to only list locally installed packages.  Prior to Chocolatey v2.0.0 `choco list` would by default search all remote sources, not just locally installed packages.  To search for locally installed packages, you would have to use `choco list --local-only`, (or other alternatives to that option, such as `-l`).

So to summarize, in Chocolatey v2.0.0 you use `choco list` to list locally installed packages, and `choco search` to list packages from remote sources.  In earlier versions of Chocolatey, `choco list` could list both locally installed and remote sources.  This was called out in our upgrade guide here: https://docs.chocolatey.org/en-us/guides/upgrading-to-chocolatey-v2-v6#the-list-command-now-lists-local-packages-only-and-the-local-only-and-lo-options-have-been-removed

In the PR that you mention above, you were removing the usage of the `chocolatey` shim, since this was also removed in v2.0.0, so when seeing that, I suggested that you also correct the usage of `choco list` for the new default behaviour.  If you are still using earlier versions of Chocolatey CLI in some other places, then `choco list` will be doing searches of remote sources, not just locally installed packages.

Hope that makes sense.

**Comment by mr-tz** [comment]
Thanks for the details and clarification. We'll want to support v2.0.0 and newer moving forward and I've updated a few other places in the linked PR.

However, the original issue appears to persist in 1.4 and 2.0. Maybe it's a Boxstarter bug?

**Comment by gep13** [comment]
Short answer is, I am not sure.  Perhaps @mwallner or @flcdrg might be able to provide some better insight here?

**Comment by dimfot3** [comment]
do we have any quick fix for this?

**Comment by mwallner** [comment]
watch out for [Boxstarter 3.0.2](https://github.com/chocolatey/boxstarter/milestone/10) - should be ready soon.

**Comment by JuanParaCatala** [comment]
![image](https://github.com/mandiant/flare-vm/assets/44454859/653b9840-dc4a-4b62-8372-f54a1181e244)

**Comment by JuanParaCatala** [comment]
I have tried to downgrade choco to v1.3.0 but I keep getting the same error.
Please help!!
I thought the issue was with choco v2 and v1.4

**Comment by Ana06** [comment]
https://github.com/mandiant/VM-Packages/pull/429 added support for Chocolatey v2 and removed support for Chocolatey < 2. But as there is a bug in Boxstarter that breaks `choco list`, **FLARE-VM doesn't work at the moment for any Chocolatey version.**

We have two options:
- Wait for the release of Boxstarter 3.0.2 that should work with Chocolatey 2.
- Revert https://github.com/mandiant/VM-Packages/pull/429 (that would work with Chocolatey 1.4) and update the FLARE-VM installer to require Chocolatey 1.4.

@mwallner thanks for taking a look into this and for the fix! When can we expect the release of Boxstarter 3.0.2? 

@gep13 thanks for the explanations!

**Comment by mwallner** [comment]
@Ana06 I'd suggest you wait for Boxstarter 3.0.2 (if possible), I *think* it should only be a matter of a day or two.
CC @gep13

**Comment by dimfot3** [comment]
This problem should have been resolved, the version Boxstarter 3.0.2 is now available

**Comment by gep13** [comment]
It would be great to get confirmation if this problem is now resolved.  Has anyone been able to take this for a spin?

**Comment by Ana06** [comment]
Installing flare-vm with Boxstarter 3.0.2 and Chocolatey 2.0.0 works 🎉  Thanks everybody for the help and the quick release of the fix! 😊 

https://github.com/mandiant/flare-vm/pull/462 requires the newest versions of Boxstarter and Chocolatey and include choco 2.0.0 command fixes.
