### ISSUE TITLE
Fail to install FLARE VM

### ISSUE THREAD

**Issue by Baskettto2** [mandiant/flare-vm#472]
### Description

When attempting to install FLARE VM an error occurred. 

### Steps to Reproduce

1. Open a PowerShell prompt as administrator
2. Download the installation script [installer.ps1](https://raw.githubusercontent.com/mandiant/flare-vm/main/install.ps1) to my desktop

    (New-Object net.webclient).DownloadFile('https://raw.githubusercontent.com/mandiant/flare-vm/main/install.ps1',"$([Environment]::GetFolderPath("Desktop"))\install.ps1")
3. Unblock the installation script by running:

    Unblock-File .\install.ps1
4. Enable script execution by running:

    Set-ExecutionPolicy Unrestricted
5.  Execute the installer script as follow:

    .\install.ps1

**Expected behavior:**
Application installs successfully

**Actual behavior:**

<img width="445" alt="issue" src="https://github.com/mandiant/flare-vm/assets/66002115/e6fd5960-6ccd-4ec1-b1f3-c66b0817c184">

**Comment by HuskyHacks** [comment]
This is -possibly- due to myget.org being down right now:

![image](https://github.com/mandiant/flare-vm/assets/57866415/82c282d3-8493-4c5e-8108-63031cb0e401)

**Comment by wvdgoot** [comment]
I have a very similar issue.

> This is -possibly- due to myget.org being down right now:

At the time myget.org seems to be up again. However, de url in the API to the common.vm package is redirecting to a dead page:

https://www.myget.org/F/vm-packages/api/v2/package/common.vm 

redirects to 

https://az774065.vo.msecnd.net/privatefeedvm0packages/common.vm-0.0.0.20230714?sv=2015-12-11&sr=b&sig=89xD%2F0kcELWsOUBiM7Oj3pk3Ny6eZ2f66sZq4i4HjDQ%3D&st=2023-07-27T09%3A55%3A00Z&se=2023-07-27T11%3A05%3A00Z&sp=r&rscc=max-age%3D3600&rsct=binary%2Foctet-stream&rscd=filename%3Dcommon.vm.0.0.0.20230714.nupkg

**Comment by devilbat4202** [comment]
Still can not install

**Comment by ckennington42** [comment]
I'm having the same issue as everyone else, I've been keeping an eye here:
https://status.myget.org/ some services have been restored, just not the ones we need.

**Comment by W1z4rd-0n3** [comment]
I have the same issue as above.

![image](https://github.com/mandiant/flare-vm/assets/97038444/d41acee4-c2ac-42ce-a313-e6cd268c4146)

Does anybody know when myget.org will be functional. And do I need to start the installation from scratch or just resume from here?

**Comment by GustavPinho** [comment]
I've been getting exactly the same error. no myget.org for me : (

**Comment by Ily455** [comment]
Hello everyone,
Try this:
https://www.myget.org/feed/vm-packages/package/nuget/common.vm/0.0.0.20230714

**Comment by wvdgoot** [comment]
The API for the packages seems to be up again. I got my `install.ps1` working for me!

**Comment by GustavPinho** [comment]
Habemus lucem!!!!

**Comment by NatchanonBR** [comment]
I get error Failures
 - common.vm - Unable to resolve dependency 'googlechrome': Unable to resolve dependencies. 'googlechrome 115.0.5790.110' is not compatible with 'cyberchef.vm 10.4.0.20230628 constraint: googlechrome (= 114.0.5735.199)'.

does anyone have this issue ?

**Comment by GustavPinho** [comment]
Da. But it keeps on pounding. At least for now. I'm still in the Cygwin phase.

**Comment by wade764** [comment]
> I am having this issue as well. It looks like myget.org is back online but I am still recieving the error "common.cm not installed. An error occurred during installation." ![VirtualBox_PMAT-FlareVM_27_07_2023_11_09_27](https://user-images.githubusercontent.com/89586330/256592940-727c6a77-fda8-4c55-b57a-e16532063f92.png)

The installation script seems to be working for me at the moment. Some additional packages have failed however (sysinternals, sysinternals.vm, and the stringsifter library related to python) Google chrome also failed but I had already installed that manually prior to Flare-VM installation.

**Comment by W1z4rd-0n3** [comment]
I am still getting the common.vm error. Anyone completed the whole installation without errors?

**Comment by frtoor** [comment]
MyGet package downloading appears to be operational, common.vm successfully installed, I have completed the script and installed Flare. Packages that failed:
sysinternals
GoogleChrome
sysinternals.vm
libraries.python3.vm

Have yet to troubleshoot those.

**Comment by akram-alkhateeb** [comment]
> I get error Failures
> 
> * common.vm - Unable to resolve dependency 'googlechrome': Unable to resolve dependencies. 'googlechrome 115.0.5790.110' is not compatible with 'cyberchef.vm 10.4.0.20230628 constraint: googlechrome (= 114.0.5735.199)'.
> 
> does anyone have this issue ?

I had to manually change the version dependency in CyberChef.vm.nupkg to the latest installed version.
1- locate chocolatey\lib\cyberchef.vm
2- open cyberchef.vm.nupkg with 7z (just open, dont extract)
3- edit cyberchef.vm.nuspec by changing the version dependency from 114.x.x.x to the latest version of google chrome (install it manually and get the version from the help button)
4- save the edited version and exit (keep in mind you are editing a packaged file so if it asked for update allow it)

this has worked for me fine after few hours of troubleshooting. I already placed an issue in Package-VM issue tracker to either update or remove the version constraint from CyberChef.vm

**Comment by frtoor** [comment]
> > I get error Failures
> > 
> > * common.vm - Unable to resolve dependency 'googlechrome': Unable to resolve dependencies. 'googlechrome 115.0.5790.110' is not compatible with 'cyberchef.vm 10.4.0.20230628 constraint: googlechrome (= 114.0.5735.199)'.
> > 
> > does anyone have this issue ?
> 
> I had to manually change the version dependency in CyberChef.vm.nupkg to the latest installed version. 1- locate chocolatey\lib\cyberchef.vm 2- open cyberchef.vm.nupkg with 7z (just open, dont extract) 3- edit cyberchef.vm.nuspec by changing the version dependency from 114.x.x.x to the latest version of google chrome (install it manually and get the version from the help button) 4- save the edited version and exit (keep in mind you are editing a packaged file so if it asked for update allow it)
> 
> this has worked for me fine after few hours of troubleshooting. I already placed an issue in Package-VM issue tracker to either update or remove the version constraint from CyberChef.vm



Have you tried installing the latest version of Chrome prior to running the script?

**Comment by akram-alkhateeb** [comment]
> Have you tried installing the latest version of Chrome prior to running the script?

actually yes, i had google chrome installed prior in my installation base image. however, for the trouble shooting i had remove it and let the script install it. no surprise it installed the latest version of Chrome. 
I also had to find the binary of 114.x.x.x that it required and installed it to no avail.
it wouldn't matter what you do, unless the dependency constraint fixed/removed from cyberchef.vm the issue will persist and even prevent choco from installing anything even if not remotely related to chrome or cyberchef.

**Comment by NatchanonBR** [comment]
> 

I have no idea  what to do or what files to modify, so I deleted cyberchef.vm and Google.vm from C:\ProgramData\chocolatey\lib. PS Script to continue working

**Comment by NatchanonBR** [comment]
I have no idea what to do or what files to modify, so I deleted cyberchef.vm and Google.vm from C:\ProgramData\chocolatey\lib. PS Script to continue working

**Comment by akram-alkhateeb** [comment]
Here:
1- Navigate to `C:\ProgramData\Chocolatey\lib\cyberchef.vm`

![1](https://github.com/mandiant/flare-vm/assets/10480402/0b0f74af-07f7-4928-9171-c6b07515b647)

2- Open `cyberchef.vm.nupkg` with 7z (or any archiver. open it, don't extract it). you might need to copy it to Desktop or any directory first!.

![2](https://github.com/mandiant/flare-vm/assets/10480402/c5bec8c5-6474-4ff9-a1be-31115cb54aa8)

3- Edit `cyberchef.vm.nuspec` file (without extracting) and modify the version in `<dependency id="googlechrome" version ="[115.0.5790.110]"` to whatever current version of google chrome.

![3](https://github.com/mandiant/flare-vm/assets/10480402/b08c8d9b-4651-44c3-b32c-9bda6c566129)

![4](https://github.com/mandiant/flare-vm/assets/10480402/b527c7af-3600-4aab-aeea-ec1d068ae280)

4- return the `cyberchef.vm.nupkg` back to the directory `C:\ProgramData\chocolatey\lib\` (if you edited it outside) and run flare-vm `install.ps1` again.

this is only a workaround (that worked for me), until the VM-Packages repository get updated

**Comment by W1z4rd-0n3** [comment]
Does anyone have any idea how to solve this -

![image](https://github.com/mandiant/flare-vm/assets/97038444/a1936ec2-70cc-42e8-a6c1-ecb8a0ac4a49)

**Comment by mcsqr50** [comment]
I'm having the same issue. Any suggestions would be appreciated. 
> Does anyone have any idea how to solve this -
> 
> ![image](https://user-images.githubusercontent.com/97038444/257012025-a1936ec2-70cc-42e8-a6c1-ecb8a0ac4a49.png)

**Comment by devilbat4202** [comment]
hi team, Could anyone install without issue?

**Comment by Baskettto2** [comment]
Installation works fine. That inconvenience was occurred due to not availability of myget.org.
