### ISSUE TITLE
Correct

### ISSUE THREAD

**Issue by MasterLantu** [mandiant/flare-vm#474]
choco install -y sysinternals.vm --ignore-checksums
pip3 install stringsifter

**Comment by MasterLantu** [comment]
choco install -y sysinternals.vm --ignore-checksums

**Comment by Ana06** [comment]
Closing this as I am not sure what you mean. Please open a new issue with more details if you think this still applies. When reporting bugs use the issue template and provide all the required information including the output of `VM-Get-Host-Info` .
