### ISSUE TITLE
VC Runtimes

### ISSUE THREAD

**Issue by stevemk14ebr** [mandiant/flare-vm#483]
Include the older visual c++ runtime redistributables for increased compatibility with older malware.

From: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

VC 2012
X86 	11.0.61030.0 	[en_visual_cpp_redistributable_for_visual_studio_2012_update_4_x86_3161523.exe](https://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x86.exe)
X64 	11.0.61030.0 	[en_visual_cpp_redistributable_for_visual_studio_2012_update_4_x64_3161523.exe](https://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe)

VC 2013
X86 	12.0.40664.0 	[vcredist_x86.exe](https://aka.ms/highdpimfc2013x86enu)
X64 	12.0.40664.0 	[vcredist_x64.exe](https://aka.ms/highdpimfc2013x64enu)

VC 2015, 2017, 2018, 2019, and 2022 all use the same redistributable. We should always choose the latest for maximum compatibility.
X86 https://aka.ms/vs/17/release/vc_redist.x86.exe
X64 https://aka.ms/vs/17/release/vc_redist.x64.exe

Our internal labs for example require VC 2013 to run correctly

**Comment by Ana06** [comment]
I think adding https://community.chocolatey.org/packages/vcredist-all to the config should fix this issue as it should include vcredist2005-2017
