### ISSUE TITLE
Ensure choco version is supported and there is internet connection before displaying GUI.

### ISSUE THREAD

**Issue by skirge** [mandiant/flare-vm#486]
### Description

I'm trying to install flare-vm on freshly imported MSEdge - Win10 VM image from Microsoft (I was using it year ago for fresh install without problem) and package list shown is empty. 
Config.xml downloaded by the script contains some packages.
Tried to use -customConfig but no change.

### Steps to Reproduce

1. Import MSEdge testing VM
2. Try to install according to manual

**Expected behavior:**

List of packages is not empty and packages are installed

**Actual behavior:**

There are no tools installed

### Environment

- VirtualBox 7.0
- Windows 

### Additional Information

![flare_no_packages](https://github.com/mandiant/flare-vm/assets/213444/304652e3-2167-4a69-8edb-d42de09205be)

**Comment by naacbin** [comment]
It's because you don't run the latest version of choco (at least v2.0.0 is required) #471

**Comment by Ana06** [comment]
Thanks for the PR @naacbin. I think we should ensure the choco/boxstarter versions are compatible and that there is an internet connection before starting the GUI.

**Comment by Ana06** [comment]
Related https://github.com/mandiant/flare-vm/issues/486
