### ISSUE TITLE
.\install.ps1 doesn't exist

### ISSUE THREAD

**Issue by Raycoug22** [mandiant/flare-vm#487]
I was trying to install .\install.ps1 but in powershell it says is not recognized 
![20230918_022733](https://github.com/mandiant/flare-vm/assets/145325718/014f3c76-b10b-4fbc-9030-cfd258377e14)

**Comment by HuskyHacks** [comment]
@Raycoug22 it's hard to tell for sure but if you follow the repo instructions, `install.ps1` ends up on your user's desktop. You're attempting to run the script from the `C:\Windows\system32` directory as your CWD.

**Comment by Ana06** [comment]
@HuskyHacks I think that's the issue as well. I'll send a PR to try to make the documentation clearer.
