### ISSUE TITLE
Powershell Error

### ISSUE THREAD

**Issue by ganeshsankaran1997** [mandiant/flare-vm#489]
Hi All I have installed install.ps1 file. But there is an issue that comes up when I try to execute powershell script at line 339 it throws an error like it cannot to remote server. Please guide me or release updated code.

![Error Image](https://github.com/mandiant/flare-vm/assets/146115243/eca93e3a-776d-475e-9163-db8269eed1c0)

**Comment by ganeshsankaran1997** [comment]
@Ana06 or team could anyone pls help me on this

**Comment by mr-tz** [comment]
Can you double-check that your VM and PowerShell have Internet access?

**Comment by ganeshsankaran1997** [comment]
Hi dude yes I do have internet access

**Comment by ganeshsankaran1997** [comment]
Ok I will try. Can you guide me after this. Now after I download this what's the next step as such. Once again I will have to star installing script install.ps1 or how ?

**Comment by mr-tz** [comment]
Yes, try running install.ps1 again.

**Comment by ganeshsankaran1997** [comment]
Hello you mean after doing with config then powershell install ps1?

**Comment by Ana06** [comment]
@ganeshsankaran1997 the error says it is not able to connect to the remote server, which means the error is not related to the flare-vm installer, but with your internet connection. You need to ensure that you have an internet connection in your VM and from your PowerShell console before being able to install flare-vm.

**Comment by ganeshsankaran1997** [comment]
Hello @Ana06 I do have internet connection in my VM that's why was able to download the zip file to VM. I am able to browse other searches in VM in edge and am getting results. If no internet connection then even my edge should have shown no internet which in this case not like that as such. Please help me out in this.
