### ISSUE TITLE
Improve documentation in README

### ISSUE THREAD

**Issue by ganeshsankaran1997** [mandiant/flare-vm#493]
Hi Team,

While installation of powershell script I recieve following error. Please fix a solution for it.

![image](https://github.com/mandiant/flare-vm/assets/146115243/f1600f93-6f20-4f70-aa82-6d750b7add75)

**Comment by Ana06** [comment]
It seems you don't have internet connection. You need an internet connection in the VM during the FLARE-VM installation.

**Comment by Ana06** [comment]
Maybe we should make this clearer in the documentation. 🤔

**Comment by wand3rlust** [comment]
@Ana06, created https://github.com/mandiant/flare-vm/pull/504 addressing this issue

**Comment by Ana06** [comment]
Thanks @wand3rlust, I am keeping this open as I would like to add some documentation improvements after https://github.com/mandiant/flare-vm/issues/510, including:
- Add a requirements section with the checks we have in the code
- Remove steps that are not necessary
- Simplify some parts of the documentation
- Update screenshots

**Comment by Ana06** [comment]
@wand3rlust when I send the PR, I would appreciate your feedback on it. 😉
