### ISSUE TITLE
Failure to install FlareVM due to existing folder

### ISSUE THREAD

**Issue by theSSDON** [mandiant/flare-vm#495]
I tried installing FlareVM on a brand new VM, with a new Windows ISO. The error states that there is already a version of Chocolatey installed at ProgramData\Chocolatey
This is the first time I tried installing it on this machine.

I deleted the said folder (which was empty), but the issue is still persisting

![Screenshot 2023-10-04 224202](https://github.com/mandiant/flare-vm/assets/71142346/a613d194-097b-465b-8a7e-41b250e02994)

**Comment by IT-Yohan** [comment]
Hello, ran into the same issue, latest Windows dev ISO. 
Just install Chocolatey separately, restart your terminal and it will run.

**Comment by theSSDON** [comment]
> Hello, ran into the same issue, latest Windows dev ISO on Hyper-V. Just install Chocolatey separately, restart your terminal and it will run.

Thank you very much! It worked

**Comment by theSSDON** [comment]
> Hello, ran into the same issue, latest Windows dev ISO on Hyper-V. Just install Chocolatey separately, restart your terminal and it will run.

Thank you very much! It worked
