### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by Naga-Chinta** [mandiant/flare-vm#500]
![error](https://github.com/mandiant/flare-vm/assets/145407592/db0a8bd5-4565-4971-b921-9f227a29171e)
I am getting this error and am unable to install Flare VM. 
I followed these steps aswell:
#Opened services.msc and disabled Windows defender and Windows Updater
#Opend an administrator powershell, navigated to the unzipped downloaded flare-vm directory
type commands;
Set-ExecutionPolicy Unrestricted
.\install.ps1

**Comment by mr-tz** [comment]
See #481?

**Comment by Ana06** [comment]
When reporting bugs, please use the bug issue template and provide all the information required there including the Powershell version. This is likely caused by the use of an old Powershell version.
