### ISSUE TITLE
Configuration: Pin taskbar icons

### ISSUE THREAD

**Issue by Ana06** [mandiant/flare-vm#512]
### Details

Pin the following icons to the taskbar:
- File Explorer (if possible with the Tools folder)
- cmd.exe (Run as admin)
- Chrome
- IDA
- fakenet (Run as admin)
- CFFExplorer
- procexp (Run as admin)
- Process Monitor (Run as admin)
- notepad++

This is to be add to the default config file (config.xml). We can probably implement this similarly as in https://github.com/mandiant/VM-Packages/blob/6423a6184172bd7a2af51eb1554551d8f45d7553/packages/debloat.vm/tools/win10.xml#L164

Requires https://github.com/mandiant/flare-vm/issues/510

**Comment by Ana06** [comment]
depending how easy the code is, we could consider adding a helper function in common. This also could be used by commando-vm and directly by the users (for example to change the taskbar in a provided VM with flare-vm installed).

**Comment by Ana06** [comment]
Idea: Use [syspin](https://community.chocolatey.org/packages/syspin). We may need to create a Chocolatey Shortcut (since that supports the `-RunAsAdmin` flag) to star tools as admin.

**Comment by Ana06** [comment]
For ida, see https://github.com/mandiant/VM-Packages/issues/694

**Comment by emtuls** [comment]
@Ana06 Unfortunately, `syspin` only works to pin `.exe` files and won't work with shortcuts/links and I was unable to find a simple set of powershell commands to make this work.

One option I looked into that seems promising is to use a custom Start Layout: https://learn.microsoft.com/en-us/windows/configuration/windows-10-start-layout-options-and-policies

We can create an `.xml` file that contains the paths to shortcuts/executables that we want pinned to the taskbar. Initial testing seems like this method would work, but this would require adding a new `CustomStartLayout.xml` somewhere such that the following Powershell command can be run:
`Import-StartLayout -LayoutPath "C:\Path\To\CustomStartLayout.xml" -MountPath "C:\"`

Would this be a viable option to consider?

**Comment by Ana06** [comment]
> File Explorer (if possible with the Tools folder)

Extracting this into https://github.com/mandiant/flare-vm/issues/535 to have more independent issues, as is is not the main goal of this issue.
