### ISSUE TITLE
Configuration: Free up space

### ISSUE THREAD

**Issue by Ana06** [mandiant/flare-vm#517]
### Details

- [ ] Delete all files in the Desktop except Recycle Bin, Tools and fakenet_logs.
- [ ] Execute as admin in cmd del /q /S %TEMP% && rmdir /S /Q "%TEMP%\chocolatey" "%LOCALAPPDATA%\NuGet\cache" "%PROGRAMDATA%\Package Cache"
- [ ] Run Disk-Cleanup (select all)
- [ ] Execute as admin in cmd sdelete -z C:

**Comment by Ana06** [comment]
Ideally we add this to a helper in common so that it can be run after installing extra packages

**Comment by emtuls** [comment]
I've added these commands into separate functions inside of `common.vm` (as per how I interpreted your 2nd comment). We can create a singular function that incorporates all of them if desired. I left it this way until we decide the best route to take.

See the PR in `VM-Packages`: https://github.com/mandiant/VM-Packages/pull/747
