### ISSUE TITLE
FlareVM won't install, errors out in both windows 10 and 11.

### ISSUE THREAD

**Issue by NixonSchool** [mandiant/flare-vm#523]
### What's the problem?

Flarevm won't install in both windows 11 and 10.

![image](https://github.com/mandiant/flare-vm/assets/139177099/af42c600-606b-42dc-8e6d-86c34aa64247)

### Steps to Reproduce

The image shows everything. I have policy unrestricted, windefender disabled, ethernet connected, what's wrong with the scripts? And the download speeds of flarevm, that's a waste of time. I have ethernet with a download, upload of 20mb/s. Why not just download everything like visual studio community, then install them later. FlareVM last time installed in 1 day, 1 freaking day. What the heck?

### Environment

**VMWare windows 10** 

![image](https://github.com/mandiant/flare-vm/assets/139177099/b968daf2-7e4b-41fe-827e-acf0882cb2ae)

![image](https://github.com/mandiant/flare-vm/assets/139177099/ca64eb74-bcf6-4b1e-bf65-3a7f1f8b366f)

![image](https://github.com/mandiant/flare-vm/assets/139177099/f834a144-016b-4f88-bf6d-1a7438d93942)

![image](https://github.com/mandiant/flare-vm/assets/139177099/dc624450-b9cd-494d-80fc-faa95dfeb549)

![image](https://github.com/mandiant/flare-vm/assets/139177099/3d2b3797-2f01-4fb2-9c66-ad51ec3e1c73)

**VMWare Windows 11**

![image](https://github.com/mandiant/flare-vm/assets/139177099/e58b0066-7038-4fe8-96a6-c47be941b0ba)

![image](https://github.com/mandiant/flare-vm/assets/139177099/72342852-f14c-4fed-aa62-b6b9d8c1fdee)

![image](https://github.com/mandiant/flare-vm/assets/139177099/9b77686d-1c6a-4d23-9c45-6d6bf4ae3c06)

### Additional Information

**Windows 10**

[log.txt](https://github.com/mandiant/flare-vm/files/13186924/log.txt)
[chocolatey.log](https://github.com/mandiant/flare-vm/files/13186925/chocolatey.log)
[choco.summary.log](https://github.com/mandiant/flare-vm/files/13186926/choco.summary.log)

**Windows 11**

[log.txt](https://github.com
[choco.summary.log](https://github.com/mandiant/flare-vm/files/13187025/choco.summary.log)
[chocolatey.log](https://github.com/mandiant/flare-vm/files/13187026/chocolatey.log)
/mandiant/flare-vm/files/13187013/log.txt)

**Comment by NixonSchool** [comment]
[chocolatey.log](https://github.com/mandiant/flare-vm/files/13187100/chocolatey.log)
[choco.summary.log](https://github.com/mandiant/flare-vm/files/13187102/choco.summary.log)
[log.txt](https://github.com/mandiant/flare-vm/files/13187103/log.txt)

uploading incase the log files didn't upload well.

**Comment by NixonSchool** [comment]
I fixed it by using an old version 3...

![version 3 works without issues](https://github.com/mandiant/flare-vm/assets/139177099/d16d9957-f39d-4654-a04b-85ec77781eef)

![image](https://github.com/mandiant/flare-vm/assets/139177099/b6ff4b79-8cec-462b-8aeb-faf70fc040af)

**Comment by Ana06** [comment]
It is failing when downloading the installation script with a 404. As documentated in [the requirements in the README](https://github.com/mandiant/flare-vm#requirements) you need internet connection to be able to install flare-vm. Please ensure that you have internet connection and retry.

**Comment by Ana06** [comment]
Assuming this is fixed due to inactivity. Closing
