### ISSUE TITLE
Disable Microsoft Connectivity Test (msftconnecttest.com)

### ISSUE THREAD

**Issue by jstrosch** [mandiant/flare-vm#525]
### Details

I've noticed when doing any sort of packet capture (i.e. fakenet-ng) that the MS connectivity test is active (i.e. DNS queries to msftconnecttest.com). Some brief testing/reading and it looks like modifying
```EnableActiveProbing```
at
```HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\NlaSvc\Parameters\Internet``` 
to zero stops this. This would be helpful to eliminate some of the background noise :) Thanks!

**Comment by Ana06** [comment]
Thanks for the issue @jstrosch! 👍 @mandiant/commando-vm  is this also something you want? Should we add it to the debloat package?

**Comment by day1player** [comment]
@Ana06 Yeah I think that sounds good!
