### ISSUE TITLE
Old Wallpaper URL no longer reachable

### ISSUE THREAD

**Issue by Gn0ky** [mandiant/flare-vm#526]
### What's the problem?

The old wallpaper address is not accessible (error 404 - not found). 
On line 848 of the "install.ps1" script, I replaced the old address with "https://github.com/mandiant/flare-vm/blob/main/Images/flarevm-background.png". 

Update required. 
Thanks ;-)

### Steps to Reproduce

-

### Environment

VM Win10x64 with VMWare.

### Additional Information

![image](https://github.com/mandiant/flare-vm/assets/116389130/56d9a55d-d57d-46f2-902e-6b76615eab7f)
![image](https://github.com/mandiant/flare-vm/assets/116389130/920fc852-54f6-41aa-a950-87373a28270e)
![image](https://github.com/mandiant/flare-vm/assets/116389130/8aa851e6-86bd-4610-8b89-bc67d4369c75)

**Comment by Ana06** [comment]
The url to download the image is `https://raw.githubusercontent.com/mandiant/flare-vm/main/Images/flarevm-background.png`, the url you are trying to use is the GH page that displays that image and that is not what you want. That is what is used in [the latest version of the installer](https://github.com/mandiant/flare-vm/blob/main/install.ps1#L863).

As mentioned in the bug issue template, please use the latest version of the installer and do not report bugs for previous versions.
