### ISSUE TITLE
install.ps1

### ISSUE THREAD

**Issue by saisumanth955** [mandiant/flare-vm#549]
### What's the problem?

install.ps1 is not getting downloaded 

### Steps to Reproduce

Jst right click and select save file

### Environment

Windows 10 in VM ware

**Comment by mr-tz** [comment]
How are you doing this (in a browser?) And what happens instead?

**Comment by saisumanth955** [comment]
It is giving network error and I am using edge. Even in my another laptop
as well I am getting the same error

**Comment by mr-tz** [comment]
Looks like you have some networking (proxy?) issues. Can you access GitHub otherwise in the VM?

**Comment by mr-tz** [comment]
Hm, that's very sad and unfortunately I cannot help you much more debugging or fixing this. Hopefully, you can find some help online or from a local admin or friend. If you think there's anything else we can do to help, please reopen the issue here.

**Comment by saisumanth955** [comment]
How can you close without giving the solution
