### ISSUE TITLE
Link CyberChef instead of GoogleChrome to taskbar

### ISSUE THREAD

**Issue by Ana06** [mandiant/flare-vm#559]
### Details

Link CyberChef instead of Google Chrome to taskbar or open CyberChef as default main page in Google Chrome. This requires modifying flare-vm and/or VM-Packages.

Issues that may be related: https://github.com/mandiant/VM-Packages/issues/823, https://github.com/mandiant/VM-Packages/issues/822, https://github.com/mandiant/VM-Packages/issues/725, https://github.com/mandiant/VM-Packages/issues/296

**Comment by emtuls** [comment]
1. Chrome seems to change where they put their user preferences for homepages often enough that I don't think programmatically adjusting the preferences file to set the default homepage is going to be a good option for long term (but we can consider it if need be).

2. Attempting to set the homepage to a local file (the `cyberchef .html file`) via `chrome://policy` did not work. It seems to prohibit the use of local files.

3. I think merging the fixes for these 2 issues will give me the ground I need to make a good alternative (using a command prompt shortcut): 
- https://github.com/mandiant/VM-Packages/issues/842
- https://github.com/mandiant/VM-Packages/issues/843

**Comment by Ana06** [comment]
We need to merge https://github.com/mandiant/flare-vm/issues/559 to close this (I modified the description so that it happens automatically)

**Comment by emtuls** [comment]
I think you might mean https://github.com/mandiant/flare-vm/pull/562? 🙂
