### ISSUE TITLE
Add PowerShell to taskbar

### ISSUE THREAD

**Issue by Ana06** [mandiant/flare-vm#563]
### Details

I think it would be useful to add a PowerShell to the taskbar that runs with admin rights and starts in the user Desktop. @emtuls what do you think? Would you like to work on this?

**Comment by emtuls** [comment]
I can make that happen. 🙂

I personally don't use powershell too much outside of testing things here and there, but I do think there could be some use for others!

**Comment by Ana06** [comment]
Documention discussion outside this issue: We agreed to add the Microsoft Windows terminal package to test if that would be a better option for our taskbar. PR to add the package in https://github.com/mandiant/VM-Packages/pull/876
