### ISSUE TITLE
Create a `sharedconfig.xml` for FlareVM & CommandoVM

### ISSUE THREAD

**Issue by emtuls** [mandiant/flare-vm#564]
### Details

Currently, we have separate configs for FlareVM and CommandoVM. Things that are shared between the two have been placed inside of the `debloat.vm` package. While this is convenient location, if we start to put things inside of it to be shared (such as the `Cmd Here` functionality), it starts to defeat the intent of the original package (debloating).

I propose we create an additional config file that includes things to be shared across both FlareVM and CommandoVM to have a proper home for things of that nature.

**Comment by Ana06** [comment]
I think this issue should be moved to VM-Packages as it affects the code in VM-Packages (and not flare-vm) and because we should discuss any change that affects commando-vm in the common repository.
