### ISSUE TITLE
Flare vm is not able to install on windows 11 

### ISSUE THREAD

**Issue by nagasaikiran010** [mandiant/flare-vm#599]
### What's the problem?

I started the install the flare vm but at the time of chocolatey installation giving an error and immediately stopped the installation 

### Steps to Reproduce

Na

### Environment

Windows 11 on VMware

**Comment by Ana06** [comment]
please provide all the [information requested in the bug issue template](https://github.com/mandiant/flare-vm/issues/new?assignees=&labels=%3Abug%3A+bug&projects=&template=bug.yml) such as the log and console output with the error you are getting so that we can help you.

**Comment by Ana06** [comment]
Closing this issue because we are not able to fix it without the log and console output. Please re-open the issue with the required information if you are still unable to install FLARE-VM in Win11.
