### ISSUE TITLE
CAPEsolo - Portable cape sandbox

### ISSUE THREAD

**Issue by doomedraven** [mandiant/flare-vm#621]
### Details

Hello we have now portable version of cape sandbox, https://github.com/CAPESandbox/CAPEsolo it nice to get run of malware sample and get everything what you would get from normal cape. Is nice for a quick triage or unpack

**Comment by Ana06** [comment]
Thanks for the tool proposal, but as documented in the README and the issue template you see when you open an issue, we track only features related to the installer in this repository. To propose a new tool, please open an issue in [VM-Packages](https://github.com/mandiant/VM-Packages/issues/new) and select the correct issue template to provide all the information we need to create the package.
