### ISSUE TITLE
Suspicious Behavior 

### ISSUE THREAD

**Issue by ZayadAlosaimi** [mandiant/flare-vm#629]
### What's the problem?

As i was installing FlareVM i noticed multiple chrome extensions related to bitcoin were installed in my VM please confirm the reason id the code injected or not 
<img width="532" alt="Screenshot 2024-11-17 005729" src="https://github.com/user-attachments/assets/0731f2dc-f1da-4f81-9b9f-bc1b0585ea83">
  

### Steps to Reproduce

-

### Environment

Windows 11

**Comment by Ana06** [comment]
@ZayadAlosaimi we are installing the extensions with the recently introduced [`chrome.extensions.vm` package](https://github.com/mandiant/VM-Packages/blob/main/packages/chrome.extensions.vm/tools/chocolateyinstall.ps1) as they can be useful to analyse credential stealers which expect this extensions to be installed.
