### ISSUE TITLE
Background Color Changes after Final Install

### ISSUE THREAD

**Issue by redteamwill** [mandiant/flare-vm#637]
### What's the problem?

I have restarted, redownloaded, and followed the exact steps for installation. After it is completed, I am left with this screen. After seeing other people's installation, their background is normal. I downloaded Windows 10 using the link provided in the install instructions but still nothing has changed. I'm not sure what to do in this case.

My questions about possible issues:

Is it something regarding the windows product key? (although I have seen others do without and still not get this problem, I don't think that's it)
I am using VirtualBox so may it be an issue with that?
Is it a problem with the script or configuration for install?

<img width="960" alt="image" src="https://github.com/user-attachments/assets/82ed6e4e-5b81-4990-912d-8c982d43bf3c" />

### Steps to Reproduce

I followed the instructions exactly:

1. Download Windows 10
2. Disable windows updates and virus and threat protection 
3. Used the scrips provided for install
4. Everything finishes installing
5. Then the screen ends up like this

### Environment

I am using the most updated version of virtual box for hypervisor
I am using the Windows 10 2022 Updated version

**Comment by mr-tz** [comment]
This is from a tool to warn you that the internet is reachable. This may not be desirable in most malware analysis cases so is enabled by default now.
For details on disabling it if you don't want to be informed on internet connectivity I refer to one of the devs here.

**Comment by redteamwill** [comment]
@mr-tz I initially installed with internet so that it can install the tools needed from Google but plan on disconnecting once I set up my lab. Could you give me the steps to disable it if you know?

**Comment by redteamwill** [comment]
@mr-tz I was able to figure it out and your right it is just a tool to inform you if you have internet connection on. I had it installed before but it may have been an added feature recently. Thanks for the help!
