### ISSUE TITLE
add profile for weak/insecure windows 7

### ISSUE THREAD

**Issue by williballenthin** [mandiant/flare-vm#8]
suggested by @Neodyn here: https://github.com/fireeye/flare-vm/issues/2#issuecomment-320773501

> Is it possible to e.g disable UAC, disable Windows defender. Imho it would be great to create a weak / insecure windows 7.

**Comment by DBHeise** [comment]
There are several existing repos for this:

[https://github.com/GoSecure/malboxes]
and (my own)
[https://github.com/DBHeise/VM_Setup]
